const fs = require('fs');
const path = require('path');

// Read existing list
const existingList = JSON.parse(fs.readFileSync('next_500_cities.json', 'utf8'));
console.log(`Current list has ${existingList.length} cities`);

// Additional cities from other states to reach 500
const moreCities = [
  // Texas - more cities
  { name: 'Abilene', state: 'Texas', slug: 'abilene-texas' },
  { name: 'Addison', state: 'Texas', slug: 'addison-texas' },
  { name: 'Alamo', state: 'Texas', slug: 'alamo-texas' },
  { name: 'Alamo Heights', state: 'Texas', slug: 'alamo-heights-texas' },
  { name: 'Albany', state: 'Texas', slug: 'albany-texas' },
  { name: 'Alice', state: 'Texas', slug: 'alice-texas' },
  { name: 'Allen', state: 'Texas', slug: 'allen-texas' },
  { name: 'Alpine', state: 'Texas', slug: 'alpine-texas' },
  { name: 'Alton', state: 'Texas', slug: 'alton-texas' },
  { name: 'Alvin', state: 'Texas', slug: 'alvin-texas' },
  { name: 'Amarillo', state: 'Texas', slug: 'amarillo-texas' },
  { name: 'Andrews', state: 'Texas', slug: 'andrews-texas' },
  { name: 'Angleton', state: 'Texas', slug: 'angleton-texas' },
  { name: 'Anna', state: 'Texas', slug: 'anna-texas' },
  { name: 'Anson', state: 'Texas', slug: 'anson-texas' },
  { name: 'Anthony', state: 'Texas', slug: 'anthony-texas' },
  { name: 'Aransas Pass', state: 'Texas', slug: 'aransas-pass-texas' },
  { name: 'Archer City', state: 'Texas', slug: 'archer-city-texas' },
  { name: 'Argyle', state: 'Texas', slug: 'argyle-texas' },
  { name: 'Arlington', state: 'Texas', slug: 'arlington-texas' },
  { name: 'Aspermont', state: 'Texas', slug: 'aspermont-texas' },
  { name: 'Athens', state: 'Texas', slug: 'athens-texas' },
  { name: 'Atlanta', state: 'Texas', slug: 'atlanta-texas' },
  { name: 'Aubrey', state: 'Texas', slug: 'aubrey-texas' },
  { name: 'Austin', state: 'Texas', slug: 'austin-texas' },
  { name: 'Azle', state: 'Texas', slug: 'azle-texas' },
  { name: 'Baird', state: 'Texas', slug: 'baird-texas' },
  { name: 'Balch Springs', state: 'Texas', slug: 'balch-springs-texas' },
  { name: 'Ballinger', state: 'Texas', slug: 'ballinger-texas' },
  { name: 'Bandera', state: 'Texas', slug: 'bandera-texas' },
  { name: 'Bardwell', state: 'Texas', slug: 'bardwell-texas' },
  { name: 'Barstow', state: 'Texas', slug: 'barstow-texas' },
  { name: 'Bartlett', state: 'Texas', slug: 'bartlett-texas' },
  { name: 'Bastrop', state: 'Texas', slug: 'bastrop-texas' },
  { name: 'Bay City', state: 'Texas', slug: 'bay-city-texas' },
  { name: 'Baytown', state: 'Texas', slug: 'baytown-texas' },
  { name: 'Beaumont', state: 'Texas', slug: 'beaumont-texas' },
  { name: 'Beeville', state: 'Texas', slug: 'beeville-texas' },
  { name: 'Bellmead', state: 'Texas', slug: 'bellmead-texas' },
  { name: 'Bells', state: 'Texas', slug: 'bells-texas' },
  { name: 'Bellville', state: 'Texas', slug: 'bellville-texas' },
  { name: 'Belton', state: 'Texas', slug: 'belton-texas' },
  { name: 'Benbrook', state: 'Texas', slug: 'benbrook-texas' },
  { name: 'Big Lake', state: 'Texas', slug: 'big-lake-texas' },
  { name: 'Big Spring', state: 'Texas', slug: 'big-spring-texas' },
  { name: 'Bishop', state: 'Texas', slug: 'bishop-texas' },
  { name: 'Blanco', state: 'Texas', slug: 'blanco-texas' },
  { name: 'Bloomington', state: 'Texas', slug: 'bloomington-texas' },
  { name: 'Blossom', state: 'Texas', slug: 'blossom-texas' },
  { name: 'Boerne', state: 'Texas', slug: 'boerne-texas' },
  { name: 'Bogata', state: 'Texas', slug: 'bogata-texas' },
  { name: 'Bonham', state: 'Texas', slug: 'bonham-texas' },
  { name: 'Borger', state: 'Texas', slug: 'borger-texas' },
  { name: 'Bovina', state: 'Texas', slug: 'bovina-texas' },
  { name: 'Bowie', state: 'Texas', slug: 'bowie-texas' },
  { name: 'Boyd', state: 'Texas', slug: 'boyd-texas' },
  { name: 'Brackettville', state: 'Texas', slug: 'brackettville-texas' },
  { name: 'Brady', state: 'Texas', slug: 'brady-texas' },
  { name: 'Breckenridge', state: 'Texas', slug: 'breckenridge-texas' },
  { name: 'Brenham', state: 'Texas', slug: 'brenham-texas' },
  { name: 'Bridge City', state: 'Texas', slug: 'bridge-city-texas' },
  { name: 'Bridgeport', state: 'Texas', slug: 'bridgeport-texas' },
  { name: 'Broaddus', state: 'Texas', slug: 'broaddus-texas' },
  { name: 'Bronte', state: 'Texas', slug: 'bronte-texas' },
  { name: 'Brookshire', state: 'Texas', slug: 'brookshire-texas' },
  { name: 'Brownfield', state: 'Texas', slug: 'brownfield-texas' },
  { name: 'Brownsville', state: 'Texas', slug: 'brownsville-texas' },
  { name: 'Brownwood', state: 'Texas', slug: 'brownwood-texas' },
  { name: 'Bryan', state: 'Texas', slug: 'bryan-texas' },
  { name: 'Buda', state: 'Texas', slug: 'buda-texas' },
  { name: 'Buffalo', state: 'Texas', slug: 'buffalo-texas' },
  { name: 'Bullard', state: 'Texas', slug: 'bullard-texas' },
  { name: 'Burkburnett', state: 'Texas', slug: 'burkburnett-texas' },
  { name: 'Burleson', state: 'Texas', slug: 'burleson-texas' },
  { name: 'Burnet', state: 'Texas', slug: 'burnet-texas' },
  { name: 'Caldwell', state: 'Texas', slug: 'caldwell-texas' },
  { name: 'Calvert', state: 'Texas', slug: 'calvert-texas' },
  { name: 'Cameron', state: 'Texas', slug: 'cameron-texas' },
  { name: 'Canadian', state: 'Texas', slug: 'canadian-texas' },
  { name: 'Canton', state: 'Texas', slug: 'canton-texas' },
  { name: 'Canyon', state: 'Texas', slug: 'canyon-texas' },
  { name: 'Carrizo Springs', state: 'Texas', slug: 'carrizo-springs-texas' },
  { name: 'Carthage', state: 'Texas', slug: 'carthage-texas' },
  { name: 'Castroville', state: 'Texas', slug: 'castroville-texas' },
  { name: 'Celina', state: 'Texas', slug: 'celina-texas' },
  { name: 'Center', state: 'Texas', slug: 'center-texas' },
  { name: 'Centerville', state: 'Texas', slug: 'centerville-texas' },
  { name: 'Chandler', state: 'Texas', slug: 'chandler-texas' },
  { name: 'Childress', state: 'Texas', slug: 'childress-texas' },
  { name: 'Chillicothe', state: 'Texas', slug: 'chillicothe-texas' },
  { name: 'Cisco', state: 'Texas', slug: 'cisco-texas' },
  { name: 'Clarksville', state: 'Texas', slug: 'clarksville-texas' },
  { name: 'Claude', state: 'Texas', slug: 'claude-texas' },
  { name: 'Cleburne', state: 'Texas', slug: 'cleburne-texas' },
  { name: 'Cleveland', state: 'Texas', slug: 'cleveland-texas' },
  { name: 'Clifton', state: 'Texas', slug: 'clifton-texas' },
  { name: 'Clute', state: 'Texas', slug: 'clute-texas' },
  { name: 'Clyde', state: 'Texas', slug: 'clyde-texas' },
  { name: 'Coleman', state: 'Texas', slug: 'coleman-texas' },
  { name: 'College Station', state: 'Texas', slug: 'college-station-texas' },
  { name: 'Colleyville', state: 'Texas', slug: 'colleyville-texas' },
  { name: 'Colorado City', state: 'Texas', slug: 'colorado-city-texas' },
  { name: 'Columbus', state: 'Texas', slug: 'columbus-texas' },
  { name: 'Comanche', state: 'Texas', slug: 'comanche-texas' },
  { name: 'Comfort', state: 'Texas', slug: 'comfort-texas' },
  { name: 'Commerce', state: 'Texas', slug: 'commerce-texas' },
  { name: 'Conroe', state: 'Texas', slug: 'conroe-texas' },
  { name: 'Converse', state: 'Texas', slug: 'converse-texas' },
  { name: 'Coppell', state: 'Texas', slug: 'coppell-texas' },
  { name: 'Copperas Cove', state: 'Texas', slug: 'copperas-cove-texas' },
  { name: 'Corpus Christi', state: 'Texas', slug: 'corpus-christi-texas' },
  { name: 'Corsicana', state: 'Texas', slug: 'corsicana-texas' },
  { name: 'Cotulla', state: 'Texas', slug: 'cotulla-texas' },
  { name: 'Crane', state: 'Texas', slug: 'crane-texas' },
  { name: 'Crockett', state: 'Texas', slug: 'crockett-texas' },
  { name: 'Crosbyton', state: 'Texas', slug: 'crosbyton-texas' },
  { name: 'Cross Plains', state: 'Texas', slug: 'cross-plains-texas' },
  { name: 'Crowley', state: 'Texas', slug: 'crowley-texas' },
  { name: 'Crystal City', state: 'Texas', slug: 'crystal-city-texas' },
  { name: 'Cuero', state: 'Texas', slug: 'cuero-texas' },
  { name: 'Daingerfield', state: 'Texas', slug: 'daingerfield-texas' },
  { name: 'Dalhart', state: 'Texas', slug: 'dalhart-texas' },
  { name: 'Dallas', state: 'Texas', slug: 'dallas-texas' },
  { name: 'Dalworthington Gardens', state: 'Texas', slug: 'dalworthington-gardens-texas' },
  { name: 'Danbury', state: 'Texas', slug: 'danbury-texas' },
  { name: 'Dayton', state: 'Texas', slug: 'dayton-texas' },
  { name: 'De Kalb', state: 'Texas', slug: 'de-kalb-texas' },
  { name: 'De Leon', state: 'Texas', slug: 'de-leon-texas' },
  { name: 'De Soto', state: 'Texas', slug: 'de-soto-texas' },
  { name: 'Decatur', state: 'Texas', slug: 'decatur-texas' },
  { name: 'Deer Park', state: 'Texas', slug: 'deer-park-texas' },
  { name: 'Del Rio', state: 'Texas', slug: 'del-rio-texas' },
  { name: 'Denison', state: 'Texas', slug: 'denison-texas' },
  { name: 'Denton', state: 'Texas', slug: 'denton-texas' },
  { name: 'Denver City', state: 'Texas', slug: 'denver-city-texas' },
  { name: 'Devine', state: 'Texas', slug: 'devine-texas' },
  { name: 'Diboll', state: 'Texas', slug: 'diboll-texas' },
  { name: 'Dickinson', state: 'Texas', slug: 'dickinson-texas' },
  { name: 'Dimmitt', state: 'Texas', slug: 'dimmitt-texas' },
  { name: 'Donna', state: 'Texas', slug: 'donna-texas' },
  { name: 'Dripping Springs', state: 'Texas', slug: 'dripping-springs-texas' },
  { name: 'Dumas', state: 'Texas', slug: 'dumas-texas' },
  { name: 'Duncanville', state: 'Texas', slug: 'duncanville-texas' },
  { name: 'Eagle Lake', state: 'Texas', slug: 'eagle-lake-texas' },
  { name: 'Eagle Pass', state: 'Texas', slug: 'eagle-pass-texas' },
  { name: 'Early', state: 'Texas', slug: 'early-texas' },
  { name: 'Eastland', state: 'Texas', slug: 'eastland-texas' },
  { name: 'Eden', state: 'Texas', slug: 'eden-texas' },
  { name: 'Edinburg', state: 'Texas', slug: 'edinburg-texas' },
  { name: 'Edna', state: 'Texas', slug: 'edna-texas' },
  { name: 'El Campo', state: 'Texas', slug: 'el-campo-texas' },
  { name: 'El Paso', state: 'Texas', slug: 'el-paso-texas' },
  { name: 'Eldorado', state: 'Texas', slug: 'eldorado-texas' },
  { name: 'Electra', state: 'Texas', slug: 'electra-texas' },
  { name: 'Elgin', state: 'Texas', slug: 'elgin-texas' },
  { name: 'Elsa', state: 'Texas', slug: 'elsa-texas' },
  { name: 'Emory', state: 'Texas', slug: 'emory-texas' },
  { name: 'Ennis', state: 'Texas', slug: 'ennis-texas' },
  { name: 'Euless', state: 'Texas', slug: 'euless-texas' },
  { name: 'Eustace', state: 'Texas', slug: 'eustace-texas' },
  { name: 'Everman', state: 'Texas', slug: 'everman-texas' },
  { name: 'Fairfield', state: 'Texas', slug: 'fairfield-texas' },
  { name: 'Falfurrias', state: 'Texas', slug: 'falfurrias-texas' },
  { name: 'Falls City', state: 'Texas', slug: 'falls-city-texas' },
  { name: 'Farmers Branch', state: 'Texas', slug: 'farmers-branch-texas' },
  { name: 'Farmersville', state: 'Texas', slug: 'farmersville-texas' },
  { name: 'Farwell', state: 'Texas', slug: 'farwell-texas' },
  { name: 'Ferris', state: 'Texas', slug: 'ferris-texas' },
  { name: 'Flatonia', state: 'Texas', slug: 'flatonia-texas' },
  { name: 'Floresville', state: 'Texas', slug: 'floresville-texas' },
  { name: 'Flower Mound', state: 'Texas', slug: 'flower-mound-texas' },
  { name: 'Floydada', state: 'Texas', slug: 'floydada-texas' },
  { name: 'Forney', state: 'Texas', slug: 'forney-texas' },
  { name: 'Fort Stockton', state: 'Texas', slug: 'fort-stockton-texas' },
  { name: 'Fort Worth', state: 'Texas', slug: 'fort-worth-texas' },
  { name: 'Franklin', state: 'Texas', slug: 'franklin-texas' },
  { name: 'Fredericksburg', state: 'Texas', slug: 'fredericksburg-texas' },
  { name: 'Freeport', state: 'Texas', slug: 'freeport-texas' },
  { name: 'Freer', state: 'Texas', slug: 'freer-texas' },
  { name: 'Friendswood', state: 'Texas', slug: 'friendswood-texas' },
  { name: 'Friona', state: 'Texas', slug: 'friona-texas' },
  { name: 'Frisco', state: 'Texas', slug: 'frisco-texas' },
  { name: 'Fritch', state: 'Texas', slug: 'fritch-texas' },
  { name: 'Gainesville', state: 'Texas', slug: 'gainesville-texas' },
  { name: 'Galena Park', state: 'Texas', slug: 'galena-park-texas' },
  { name: 'Galveston', state: 'Texas', slug: 'galveston-texas' },
  { name: 'Garland', state: 'Texas', slug: 'garland-texas' },
  { name: 'Garrison', state: 'Texas', slug: 'garrison-texas' },
  { name: 'Gatesville', state: 'Texas', slug: 'gatesville-texas' },
  { name: 'George West', state: 'Texas', slug: 'george-west-texas' },
  { name: 'Georgetown', state: 'Texas', slug: 'georgetown-texas' },
  { name: 'Giddings', state: 'Texas', slug: 'giddings-texas' },
  { name: 'Gilmer', state: 'Texas', slug: 'gilmer-texas' },
  { name: 'Gladewater', state: 'Texas', slug: 'gladewater-texas' },
  { name: 'Glen Rose', state: 'Texas', slug: 'glen-rose-texas' },
  { name: 'Godley', state: 'Texas', slug: 'godley-texas' },
  { name: 'Goldthwaite', state: 'Texas', slug: 'goldthwaite-texas' },
  { name: 'Goliad', state: 'Texas', slug: 'goliad-texas' },
  { name: 'Gonzales', state: 'Texas', slug: 'gonzales-texas' },
  { name: 'Gorman', state: 'Texas', slug: 'gorman-texas' },
  { name: 'Graham', state: 'Texas', slug: 'graham-texas' },
  { name: 'Granbury', state: 'Texas', slug: 'granbury-texas' },
  { name: 'Grand Prairie', state: 'Texas', slug: 'grand-prairie-texas' },
  { name: 'Grand Saline', state: 'Texas', slug: 'grand-saline-texas' },
  { name: 'Grapevine', state: 'Texas', slug: 'grapevine-texas' },
  { name: 'Greenville', state: 'Texas', slug: 'greenville-texas' },
  { name: 'Gregory', state: 'Texas', slug: 'gregory-texas' },
  { name: 'Groesbeck', state: 'Texas', slug: 'groesbeck-texas' },
  { name: 'Groves', state: 'Texas', slug: 'groves-texas' },
  { name: 'Groveton', state: 'Texas', slug: 'groveton-texas' },
  { name: 'Gruver', state: 'Texas', slug: 'gruver-texas' },
  { name: 'Gun Barrel City', state: 'Texas', slug: 'gun-barrel-city-texas' },
  { name: 'Hallettsville', state: 'Texas', slug: 'hallettsville-texas' },
  { name: 'Hallsville', state: 'Texas', slug: 'hallsville-texas' },
  { name: 'Haltom City', state: 'Texas', slug: 'haltom-city-texas' },
  { name: 'Hamilton', state: 'Texas', slug: 'hamilton-texas' },
  { name: 'Hamlin', state: 'Texas', slug: 'hamlin-texas' },
  { name: 'Harker Heights', state: 'Texas', slug: 'harker-heights-texas' },
  { name: 'Harlingen', state: 'Texas', slug: 'harlingen-texas' },
  { name: 'Hart', state: 'Texas', slug: 'hart-texas' },
  { name: 'Haskell', state: 'Texas', slug: 'haskell-texas' },
  { name: 'Hawkins', state: 'Texas', slug: 'hawkins-texas' },
  { name: 'Hearne', state: 'Texas', slug: 'hearne-texas' },
  { name: 'Heath', state: 'Texas', slug: 'heath-texas' },
  { name: 'Hedwig Village', state: 'Texas', slug: 'hedwig-village-texas' },
  { name: 'Hempstead', state: 'Texas', slug: 'hempstead-texas' },
  { name: 'Henderson', state: 'Texas', slug: 'henderson-texas' },
  { name: 'Henrietta', state: 'Texas', slug: 'henrietta-texas' },
  { name: 'Hereford', state: 'Texas', slug: 'hereford-texas' },
  { name: 'Hewitt', state: 'Texas', slug: 'hewitt-texas' },
  { name: 'Hico', state: 'Texas', slug: 'hico-texas' },
  { name: 'Hidalgo', state: 'Texas', slug: 'hidalgo-texas' },
  { name: 'Higgins', state: 'Texas', slug: 'higgins-texas' },
  { name: 'Highland Park', state: 'Texas', slug: 'highland-park-texas' },
  { name: 'Highland Village', state: 'Texas', slug: 'highland-village-texas' },
  { name: 'Hillsboro', state: 'Texas', slug: 'hillsboro-texas' },
  { name: 'Hitchcock', state: 'Texas', slug: 'hitchcock-texas' },
  { name: 'Hondo', state: 'Texas', slug: 'hondo-texas' },
  { name: 'Honey Grove', state: 'Texas', slug: 'honey-grove-texas' },
  { name: 'Hooks', state: 'Texas', slug: 'hooks-texas' },
  { name: 'Houston', state: 'Texas', slug: 'houston-texas' },
  { name: 'Howe', state: 'Texas', slug: 'howe-texas' },
  { name: 'Hubbard', state: 'Texas', slug: 'hubbard-texas' },
  { name: 'Humble', state: 'Texas', slug: 'humble-texas' },
  { name: 'Huntsville', state: 'Texas', slug: 'huntsville-texas' },
  { name: 'Hurst', state: 'Texas', slug: 'hurst-texas' },
  { name: 'Hutchins', state: 'Texas', slug: 'hutchins-texas' },
  { name: 'Idalou', state: 'Texas', slug: 'idalou-texas' },
  { name: 'Ingleside', state: 'Texas', slug: 'ingleside-texas' },
  { name: 'Iowa Park', state: 'Texas', slug: 'iowa-park-texas' },
  { name: 'Irving', state: 'Texas', slug: 'irving-texas' },
  { name: 'Italy', state: 'Texas', slug: 'italy-texas' },
  { name: 'Itasca', state: 'Texas', slug: 'itasca-texas' },
  { name: 'Jacksboro', state: 'Texas', slug: 'jacksboro-texas' },
  { name: 'Jacksonville', state: 'Texas', slug: 'jacksonville-texas' },
  { name: 'Jasper', state: 'Texas', slug: 'jasper-texas' },
  { name: 'Jayton', state: 'Texas', slug: 'jayton-texas' },
  { name: 'Jefferson', state: 'Texas', slug: 'jefferson-texas' },
  { name: 'Jersey Village', state: 'Texas', slug: 'jersey-village-texas' },
  { name: 'Jewett', state: 'Texas', slug: 'jewett-texas' },
  { name: 'Johnson City', state: 'Texas', slug: 'johnson-city-texas' },
  { name: 'Jourdanton', state: 'Texas', slug: 'jourdanton-texas' },
  { name: 'Junction', state: 'Texas', slug: 'junction-texas' },
  { name: 'Juno', state: 'Texas', slug: 'juno-texas' },
  { name: 'Karnes City', state: 'Texas', slug: 'karnes-city-texas' },
  { name: 'Katy', state: 'Texas', slug: 'katy-texas' },
  { name: 'Kaufman', state: 'Texas', slug: 'kaufman-texas' },
  { name: 'Keene', state: 'Texas', slug: 'keene-texas' },
  { name: 'Keller', state: 'Texas', slug: 'keller-texas' },
  { name: 'Kemah', state: 'Texas', slug: 'kemah-texas' },
  { name: 'Kemp', state: 'Texas', slug: 'kemp-texas' },
  { name: 'Kenedy', state: 'Texas', slug: 'kenedy-texas' },
  { name: 'Kennedale', state: 'Texas', slug: 'kennedale-texas' },
  { name: 'Kermit', state: 'Texas', slug: 'kermit-texas' },
  { name: 'Kerrville', state: 'Texas', slug: 'kerrville-texas' },
  { name: 'Kilgore', state: 'Texas', slug: 'kilgore-texas' },
  { name: 'Killeen', state: 'Texas', slug: 'killeen-texas' },
  { name: 'Kingsville', state: 'Texas', slug: 'kingsville-texas' },
  { name: 'Kirby', state: 'Texas', slug: 'kirby-texas' },
  { name: 'Kirbyville', state: 'Texas', slug: 'kirbyville-texas' },
  { name: 'Knox City', state: 'Texas', slug: 'knox-city-texas' },
  { name: 'Kountze', state: 'Texas', slug: 'kountze-texas' },
  { name: 'Kyle', state: 'Texas', slug: 'kyle-texas' },
  { name: 'La Feria', state: 'Texas', slug: 'la-feria-texas' },
  { name: 'La Grange', state: 'Texas', slug: 'la-grange-texas' },
  { name: 'La Marque', state: 'Texas', slug: 'la-marque-texas' },
  { name: 'La Porte', state: 'Texas', slug: 'la-porte-texas' },
  { name: 'Lacy-Lakeview', state: 'Texas', slug: 'lacy-lakeview-texas' },
  { name: 'Lago Vista', state: 'Texas', slug: 'lago-vista-texas' },
  { name: 'Lake Dallas', state: 'Texas', slug: 'lake-dallas-texas' },
  { name: 'Lake Jackson', state: 'Texas', slug: 'lake-jackson-texas' },
  { name: 'Lake Worth', state: 'Texas', slug: 'lake-worth-texas' },
  { name: 'Lamesa', state: 'Texas', slug: 'lamesa-texas' },
  { name: 'Lampasas', state: 'Texas', slug: 'lampasas-texas' },
  { name: 'Lancaster', state: 'Texas', slug: 'lancaster-texas' },
  { name: 'Laredo', state: 'Texas', slug: 'laredo-texas' },
  { name: 'League City', state: 'Texas', slug: 'league-city-texas' },
  { name: 'Leander', state: 'Texas', slug: 'leander-texas' },
  { name: 'Leonard', state: 'Texas', slug: 'leonard-texas' },
  { name: 'Levelland', state: 'Texas', slug: 'levelland-texas' },
  { name: 'Lewisville', state: 'Texas', slug: 'lewisville-texas' },
  { name: 'Liberty', state: 'Texas', slug: 'liberty-texas' },
  { name: 'Liberty Hill', state: 'Texas', slug: 'liberty-hill-texas' },
  { name: 'Lindale', state: 'Texas', slug: 'lindale-texas' },
  { name: 'Linden', state: 'Texas', slug: 'linden-texas' },
  { name: 'Lindsay', state: 'Texas', slug: 'lindsay-texas' },
  { name: 'Little Elm', state: 'Texas', slug: 'little-elm-texas' },
  { name: 'Littlefield', state: 'Texas', slug: 'littlefield-texas' },
  { name: 'Live Oak', state: 'Texas', slug: 'live-oak-texas' },
  { name: 'Livingston', state: 'Texas', slug: 'livingston-texas' },
  { name: 'Llano', state: 'Texas', slug: 'llano-texas' },
  { name: 'Lockhart', state: 'Texas', slug: 'lockhart-texas' },
  { name: 'Lockney', state: 'Texas', slug: 'lockney-texas' },
  { name: 'Longview', state: 'Texas', slug: 'longview-texas' },
  { name: 'Lorena', state: 'Texas', slug: 'lorena-texas' },
  { name: 'Los Fresnos', state: 'Texas', slug: 'los-fresnos-texas' },
  { name: 'Lubbock', state: 'Texas', slug: 'lubbock-texas' },
  { name: 'Lufkin', state: 'Texas', slug: 'lufkin-texas' },
  { name: 'Luling', state: 'Texas', slug: 'luling-texas' },
  { name: 'Lumberton', state: 'Texas', slug: 'lumberton-texas' },
  { name: 'Lyford', state: 'Texas', slug: 'lyford-texas' },
  { name: 'Lytle', state: 'Texas', slug: 'lytle-texas' },
  { name: 'Madisonville', state: 'Texas', slug: 'madisonville-texas' },
  { name: 'Magnolia', state: 'Texas', slug: 'magnolia-texas' },
  { name: 'Malakoff', state: 'Texas', slug: 'malakoff-texas' },
  { name: 'Manor', state: 'Texas', slug: 'manor-texas' },
  { name: 'Mansfield', state: 'Texas', slug: 'mansfield-texas' },
  { name: 'Marble Falls', state: 'Texas', slug: 'marble-falls-texas' },
  { name: 'Marfa', state: 'Texas', slug: 'marfa-texas' },
  { name: 'Marlin', state: 'Texas', slug: 'marlin-texas' },
  { name: 'Marshall', state: 'Texas', slug: 'marshall-texas' },
  { name: 'Mart', state: 'Texas', slug: 'mart-texas' },
  { name: 'Mason', state: 'Texas', slug: 'mason-texas' },
  { name: 'Matador', state: 'Texas', slug: 'matador-texas' },
  { name: 'Mathis', state: 'Texas', slug: 'mathis-texas' },
  { name: 'McAllen', state: 'Texas', slug: 'mcallen-texas' },
  { name: 'McGregor', state: 'Texas', slug: 'mcgregor-texas' },
  { name: 'McKinney', state: 'Texas', slug: 'mckinney-texas' },
  { name: 'McLean', state: 'Texas', slug: 'mclean-texas' },
  { name: 'Medina', state: 'Texas', slug: 'medina-texas' },
  { name: 'Memphis', state: 'Texas', slug: 'memphis-texas' },
  { name: 'Menard', state: 'Texas', slug: 'menard-texas' },
  { name: 'Mercedes', state: 'Texas', slug: 'mercedes-texas' },
  { name: 'Meridian', state: 'Texas', slug: 'meridian-texas' },
  { name: 'Mertzon', state: 'Texas', slug: 'mertzon-texas' },
  { name: 'Mesquite', state: 'Texas', slug: 'mesquite-texas' },
  { name: 'Mexia', state: 'Texas', slug: 'mexia-texas' },
  { name: 'Midland', state: 'Texas', slug: 'midland-texas' },
  { name: 'Midlothian', state: 'Texas', slug: 'midlothian-texas' },
  { name: 'Mila Doce', state: 'Texas', slug: 'mila-doce-texas' },
  { name: 'Mineola', state: 'Texas', slug: 'mineola-texas' },
  { name: 'Mineral Wells', state: 'Texas', slug: 'mineral-wells-texas' },
  { name: 'Mission', state: 'Texas', slug: 'mission-texas' },
  { name: 'Missouri City', state: 'Texas', slug: 'missouri-city-texas' },
  { name: 'Monahans', state: 'Texas', slug: 'monahans-texas' },
  { name: 'Monroe City', state: 'Texas', slug: 'monroe-city-texas' },
  { name: 'Mont Belvieu', state: 'Texas', slug: 'mont-belvieu-texas' },
  { name: 'Montgomery', state: 'Texas', slug: 'montgomery-texas' },
  { name: 'Morton', state: 'Texas', slug: 'morton-texas' },
  { name: 'Mount Pleasant', state: 'Texas', slug: 'mount-pleasant-texas' },
  { name: 'Mount Vernon', state: 'Texas', slug: 'mount-vernon-texas' },
  { name: 'Muenster', state: 'Texas', slug: 'muenster-texas' },
  { name: 'Muleshoe', state: 'Texas', slug: 'muleshoe-texas' },
  { name: 'Nacogdoches', state: 'Texas', slug: 'nacogdoches-texas' },
  { name: 'Nederland', state: 'Texas', slug: 'nederland-texas' },
  { name: 'Needville', state: 'Texas', slug: 'needville-texas' },
  { name: 'New Boston', state: 'Texas', slug: 'new-boston-texas' },
  { name: 'New Braunfels', state: 'Texas', slug: 'new-braunfels-texas' },
  { name: 'New Caney', state: 'Texas', slug: 'new-caney-texas' },
  { name: 'New London', state: 'Texas', slug: 'new-london-texas' },
  { name: 'New Waverly', state: 'Texas', slug: 'new-waverly-texas' },
  { name: 'Newton', state: 'Texas', slug: 'newton-texas' },
  { name: 'Nocona', state: 'Texas', slug: 'nocona-texas' },
  { name: 'Nolanville', state: 'Texas', slug: 'nolanville-texas' },
  { name: 'North Richland Hills', state: 'Texas', slug: 'north-richland-hills-texas' },
  { name: 'Northlake', state: 'Texas', slug: 'northlake-texas' },
  { name: 'Odessa', state: 'Texas', slug: 'odessa-texas' },
  { name: 'Olney', state: 'Texas', slug: 'olney-texas' },
  { name: 'Olton', state: 'Texas', slug: 'olton-texas' },
  { name: 'Orange', state: 'Texas', slug: 'orange-texas' },
  { name: 'Ore City', state: 'Texas', slug: 'ore-city-texas' },
  { name: 'Overton', state: 'Texas', slug: 'overton-texas' },
  { name: 'Palestine', state: 'Texas', slug: 'palestine-texas' },
  { name: 'Palmer', state: 'Texas', slug: 'palmer-texas' },
  { name: 'Pampa', state: 'Texas', slug: 'pampa-texas' },
  { name: 'Panhandle', state: 'Texas', slug: 'panhandle-texas' },
  { name: 'Paris', state: 'Texas', slug: 'paris-texas' },
  { name: 'Pasadena', state: 'Texas', slug: 'pasadena-texas' },
  { name: 'Pearland', state: 'Texas', slug: 'pearland-texas' },
  { name: 'Pearsall', state: 'Texas', slug: 'pearsall-texas' },
  { name: 'Pecos', state: 'Texas', slug: 'pecos-texas' },
  { name: 'Perryton', state: 'Texas', slug: 'perryton-texas' },
  { name: 'Pflugerville', state: 'Texas', slug: 'pflugerville-texas' },
  { name: 'Pharr', state: 'Texas', slug: 'pharr-texas' },
  { name: 'Pilot Point', state: 'Texas', slug: 'pilot-point-texas' },
  { name: 'Pineland', state: 'Texas', slug: 'pineland-texas' },
  { name: 'Pittsburg', state: 'Texas', slug: 'pittsburg-texas' },
  { name: 'Plains', state: 'Texas', slug: 'plains-texas' },
  { name: 'Plainview', state: 'Texas', slug: 'plainview-texas' },
  { name: 'Plano', state: 'Texas', slug: 'plano-texas' },
  { name: 'Pleasanton', state: 'Texas', slug: 'pleasanton-texas' },
  { name: 'Point Comfort', state: 'Texas', slug: 'point-comfort-texas' },
  { name: 'Port Aransas', state: 'Texas', slug: 'port-aransas-texas' },
  { name: 'Port Arthur', state: 'Texas', slug: 'port-arthur-texas' },
  { name: 'Port Isabel', state: 'Texas', slug: 'port-isabel-texas' },
  { name: 'Port Lavaca', state: 'Texas', slug: 'port-lavaca-texas' },
  { name: 'Port Neches', state: 'Texas', slug: 'port-neches-texas' },
  { name: 'Post', state: 'Texas', slug: 'post-texas' },
  { name: 'Poteet', state: 'Texas', slug: 'poteet-texas' },
  { name: 'Poth', state: 'Texas', slug: 'poth-texas' },
  { name: 'Pottsboro', state: 'Texas', slug: 'pottsboro-texas' },
  { name: 'Premont', state: 'Texas', slug: 'premont-texas' },
  { name: 'Presidio', state: 'Texas', slug: 'presidio-texas' },
  { name: 'Quanah', state: 'Texas', slug: 'quanah-texas' },
  { name: 'Queen City', state: 'Texas', slug: 'queen-city-texas' },
  { name: 'Quinlan', state: 'Texas', slug: 'quinlan-texas' },
  { name: 'Quitman', state: 'Texas', slug: 'quitman-texas' },
  { name: 'Ralls', state: 'Texas', slug: 'ralls-texas' },
  { name: 'Ranger', state: 'Texas', slug: 'ranger-texas' },
  { name: 'Rankin', state: 'Texas', slug: 'rankin-texas' },
  { name: 'Raymondville', state: 'Texas', slug: 'raymondville-texas' },
  { name: 'Red Oak', state: 'Texas', slug: 'red-oak-texas' },
  { name: 'Refugio', state: 'Texas', slug: 'refugio-texas' },
  { name: 'Rhome', state: 'Texas', slug: 'rhome-texas' },
  { name: 'Richardson', state: 'Texas', slug: 'richardson-texas' },
  { name: 'Richland Hills', state: 'Texas', slug: 'richland-hills-texas' },
  { name: 'Richmond', state: 'Texas', slug: 'richmond-texas' },
  { name: 'Rio Grande City', state: 'Texas', slug: 'rio-grande-city-texas' },
  { name: 'Rio Hondo', state: 'Texas', slug: 'rio-hondo-texas' },
  { name: 'River Oaks', state: 'Texas', slug: 'river-oaks-texas' },
  { name: 'Roanoke', state: 'Texas', slug: 'roanoke-texas' },
  { name: 'Robinson', state: 'Texas', slug: 'robinson-texas' },
  { name: 'Robstown', state: 'Texas', slug: 'robstown-texas' },
  { name: 'Roby', state: 'Texas', slug: 'roby-texas' },
  { name: 'Rochester', state: 'Texas', slug: 'rochester-texas' },
  { name: 'Rockdale', state: 'Texas', slug: 'rockdale-texas' },
  { name: 'Rockport', state: 'Texas', slug: 'rockport-texas' },
  { name: 'Rocksprings', state: 'Texas', slug: 'rocksprings-texas' },
  { name: 'Rockwall', state: 'Texas', slug: 'rockwall-texas' },
  { name: 'Rogers', state: 'Texas', slug: 'rogers-texas' },
  { name: 'Rollingwood', state: 'Texas', slug: 'rollingwood-texas' },
  { name: 'Roma', state: 'Texas', slug: 'roma-texas' },
  { name: 'Rosenberg', state: 'Texas', slug: 'rosenberg-texas' },
  { name: 'Rosser', state: 'Texas', slug: 'rosser-texas' },
  { name: 'Rotan', state: 'Texas', slug: 'rotan-texas' },
  { name: 'Round Rock', state: 'Texas', slug: 'round-rock-texas' },
  { name: 'Rowlett', state: 'Texas', slug: 'rowlett-texas' },
  { name: 'Royse City', state: 'Texas', slug: 'royse-city-texas' },
  { name: 'Rule', state: 'Texas', slug: 'rule-texas' },
  { name: 'Rusk', state: 'Texas', slug: 'rusk-texas' },
  { name: 'Sabinal', state: 'Texas', slug: 'sabinal-texas' },
  { name: 'Sachse', state: 'Texas', slug: 'sachse-texas' },
  { name: 'Sadler', state: 'Texas', slug: 'sadler-texas' },
  { name: 'Saginaw', state: 'Texas', slug: 'saginaw-texas' },
  { name: 'Saint Jo', state: 'Texas', slug: 'saint-jo-texas' },
  { name: 'Salado', state: 'Texas', slug: 'salado-texas' },
  { name: 'San Angelo', state: 'Texas', slug: 'san-angelo-texas' },
  { name: 'San Antonio', state: 'Texas', slug: 'san-antonio-texas' },
  { name: 'San Augustine', state: 'Texas', slug: 'san-augustine-texas' },
  { name: 'San Benito', state: 'Texas', slug: 'san-benito-texas' },
  { name: 'San Diego', state: 'Texas', slug: 'san-diego-texas' },
  { name: 'San Elizario', state: 'Texas', slug: 'san-elizario-texas' },
  { name: 'San Juan', state: 'Texas', slug: 'san-juan-texas' },
  { name: 'San Marcos', state: 'Texas', slug: 'san-marcos-texas' },
  { name: 'San Saba', state: 'Texas', slug: 'san-saba-texas' },
  { name: 'Sanderson', state: 'Texas', slug: 'sanderson-texas' },
  { name: 'Sanger', state: 'Texas', slug: 'sanger-texas' },
  { name: 'Santa Fe', state: 'Texas', slug: 'santa-fe-texas' },
  { name: 'Saratoga', state: 'Texas', slug: 'saratoga-texas' },
  { name: 'Schertz', state: 'Texas', slug: 'schertz-texas' },
  { name: 'Schulenburg', state: 'Texas', slug: 'schulenburg-texas' },
  { name: 'Seabrook', state: 'Texas', slug: 'seabrook-texas' },
  { name: 'Seagoville', state: 'Texas', slug: 'seagoville-texas' },
  { name: 'Sealy', state: 'Texas', slug: 'sealy-texas' },
  { name: 'Seguin', state: 'Texas', slug: 'seguin-texas' },
  { name: 'Selma', state: 'Texas', slug: 'selma-texas' },
  { name: 'Seminole', state: 'Texas', slug: 'seminole-texas' },
  { name: 'Seymour', state: 'Texas', slug: 'seymour-texas' },
  { name: 'Shamrock', state: 'Texas', slug: 'shamrock-texas' },
  { name: 'Shepherd', state: 'Texas', slug: 'shepherd-texas' },
  { name: 'Sherman', state: 'Texas', slug: 'sherman-texas' },
  { name: 'Shiner', state: 'Texas', slug: 'shiner-texas' },
  { name: 'Silsbee', state: 'Texas', slug: 'silsbee-texas' },
  { name: 'Silverton', state: 'Texas', slug: 'silverton-texas' },
  { name: 'Sinton', state: 'Texas', slug: 'sinton-texas' },
  { name: 'Slaton', state: 'Texas', slug: 'slaton-texas' },
  { name: 'Smithville', state: 'Texas', slug: 'smithville-texas' },
  { name: 'Snyder', state: 'Texas', slug: 'snyder-texas' },
  { name: 'Socorro', state: 'Texas', slug: 'socorro-texas' },
  { name: 'Somerset', state: 'Texas', slug: 'somerset-texas' },
  { name: 'Somerville', state: 'Texas', slug: 'somerville-texas' },
  { name: 'Sonora', state: 'Texas', slug: 'sonora-texas' },
  { name: 'South Houston', state: 'Texas', slug: 'south-houston-texas' },
  { name: 'South Padre Island', state: 'Texas', slug: 'south-padre-island-texas' },
  { name: 'Southlake', state: 'Texas', slug: 'southlake-texas' },
  { name: 'Spearman', state: 'Texas', slug: 'spearman-texas' },
  { name: 'Splendora', state: 'Texas', slug: 'splendora-texas' },
  { name: 'Spring', state: 'Texas', slug: 'spring-texas' },
  { name: 'Spring Valley', state: 'Texas', slug: 'spring-valley-texas' },
  { name: 'Springtown', state: 'Texas', slug: 'springtown-texas' },
  { name: 'Spur', state: 'Texas', slug: 'spur-texas' },
  { name: 'Stafford', state: 'Texas', slug: 'stafford-texas' },
  { name: 'Stamford', state: 'Texas', slug: 'stamford-texas' },
  { name: 'Stanton', state: 'Texas', slug: 'stanton-texas' },
  { name: 'Stephenville', state: 'Texas', slug: 'stephenville-texas' },
  { name: 'Sterling City', state: 'Texas', slug: 'sterling-city-texas' },
  { name: 'Stinnett', state: 'Texas', slug: 'stinnett-texas' },
  { name: 'Stockdale', state: 'Texas', slug: 'stockdale-texas' },
  { name: 'Stratford', state: 'Texas', slug: 'stratford-texas' },
  { name: 'Sugar Land', state: 'Texas', slug: 'sugar-land-texas' },
  { name: 'Sulphur Springs', state: 'Texas', slug: 'sulphur-springs-texas' },
  { name: 'Sweeny', state: 'Texas', slug: 'sweeny-texas' },
  { name: 'Sweetwater', state: 'Texas', slug: 'sweetwater-texas' },
  { name: 'Taft', state: 'Texas', slug: 'taft-texas' },
  { name: 'Tahoka', state: 'Texas', slug: 'tahoka-texas' },
  { name: 'Talco', state: 'Texas', slug: 'talco-texas' },
  { name: 'Tatum', state: 'Texas', slug: 'tatum-texas' },
  { name: 'Taylor', state: 'Texas', slug: 'taylor-texas' },
  { name: 'Teague', state: 'Texas', slug: 'teague-texas' },
  { name: 'Temple', state: 'Texas', slug: 'temple-texas' },
  { name: 'Tenaha', state: 'Texas', slug: 'tenaha-texas' },
  { name: 'Terrell', state: 'Texas', slug: 'terrell-texas' },
  { name: 'Texarkana', state: 'Texas', slug: 'texarkana-texas' },
  { name: 'Texas City', state: 'Texas', slug: 'texas-city-texas' },
  { name: 'The Colony', state: 'Texas', slug: 'the-colony-texas' },
  { name: 'The Woodlands', state: 'Texas', slug: 'the-woodlands-texas' },
  { name: 'Thrall', state: 'Texas', slug: 'thrall-texas' },
  { name: 'Three Rivers', state: 'Texas', slug: 'three-rivers-texas' },
  { name: 'Tolar', state: 'Texas', slug: 'tolar-texas' },
  { name: 'Tomball', state: 'Texas', slug: 'tomball-texas' },
  { name: 'Tool', state: 'Texas', slug: 'tool-texas' },
  { name: 'Tulia', state: 'Texas', slug: 'tulia-texas' },
  { name: 'Tyler', state: 'Texas', slug: 'tyler-texas' },
  { name: 'Universal City', state: 'Texas', slug: 'universal-city-texas' },
  { name: 'University Park', state: 'Texas', slug: 'university-park-texas' },
  { name: 'Uvalde', state: 'Texas', slug: 'uvalde-texas' },
  { name: 'Van', state: 'Texas', slug: 'van-texas' },
  { name: 'Van Alstyne', state: 'Texas', slug: 'van-alstyne-texas' },
  { name: 'Vega', state: 'Texas', slug: 'vega-texas' },
  { name: 'Vernon', state: 'Texas', slug: 'vernon-texas' },
  { name: 'Victoria', state: 'Texas', slug: 'victoria-texas' },
  { name: 'Vidor', state: 'Texas', slug: 'vidor-texas' },
  { name: 'Waco', state: 'Texas', slug: 'waco-texas' },
  { name: 'Waelder', state: 'Texas', slug: 'waelder-texas' },
  { name: 'Wake Village', state: 'Texas', slug: 'wake-village-texas' },
  { name: 'Waller', state: 'Texas', slug: 'waller-texas' },
  { name: 'Watauga', state: 'Texas', slug: 'watauga-texas' },
  { name: 'Waxahachie', state: 'Texas', slug: 'waxahachie-texas' },
  { name: 'Weatherford', state: 'Texas', slug: 'weatherford-texas' },
  { name: 'Webster', state: 'Texas', slug: 'webster-texas' },
  { name: 'Weimar', state: 'Texas', slug: 'weimar-texas' },
  { name: 'Wellington', state: 'Texas', slug: 'wellington-texas' },
  { name: 'Weslaco', state: 'Texas', slug: 'weslaco-texas' },
  { name: 'West', state: 'Texas', slug: 'west-texas' },
  { name: 'West Columbia', state: 'Texas', slug: 'west-columbia-texas' },
  { name: 'West University Place', state: 'Texas', slug: 'west-university-place-texas' },
  { name: 'Wharton', state: 'Texas', slug: 'wharton-texas' },
  { name: 'Wheeler', state: 'Texas', slug: 'wheeler-texas' },
  { name: 'White Oak', state: 'Texas', slug: 'white-oak-texas' },
  { name: 'White Settlement', state: 'Texas', slug: 'white-settlement-texas' },
  { name: 'Whitehouse', state: 'Texas', slug: 'whitehouse-texas' },
  { name: 'Whitesboro', state: 'Texas', slug: 'whitesboro-texas' },
  { name: 'Whitewright', state: 'Texas', slug: 'whitewright-texas' },
  { name: 'Wichita Falls', state: 'Texas', slug: 'wichita-falls-texas' },
  { name: 'Willis', state: 'Texas', slug: 'willis-texas' },
  { name: 'Willow Park', state: 'Texas', slug: 'willow-park-texas' },
  { name: 'Wills Point', state: 'Texas', slug: 'wills-point-texas' },
  { name: 'Wilmer', state: 'Texas', slug: 'wilmer-texas' },
  { name: 'Wilson', state: 'Texas', slug: 'wilson-texas' },
  { name: 'Wimberley', state: 'Texas', slug: 'wimberley-texas' },
  { name: 'Windcrest', state: 'Texas', slug: 'windcrest-texas' },
  { name: 'Wink', state: 'Texas', slug: 'wink-texas' },
  { name: 'Winnsboro', state: 'Texas', slug: 'winnsboro-texas' },
  { name: 'Winters', state: 'Texas', slug: 'winters-texas' },
  { name: 'Wolfforth', state: 'Texas', slug: 'wolfforth-texas' },
  { name: 'Woodway', state: 'Texas', slug: 'woodway-texas' },
  { name: 'Yoakum', state: 'Texas', slug: 'yoakum-texas' },
  { name: 'Yorktown', state: 'Texas', slug: 'yorktown-texas' },
  { name: 'Zapata', state: 'Texas', slug: 'zapata-texas' },
  { name: 'Zavalla', state: 'Texas', slug: 'zavalla-texas' },
];

// Check existing pages
const existingPages = new Set();
function findExistingPages(dir) {
  try {
    const files = fs.readdirSync(dir);
    for (const file of files) {
      const fullPath = path.join(dir, file);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        findExistingPages(fullPath);
      } else if (file === 'pageClient.tsx') {
        const match = fullPath.match(/vending-leads[\/\\]([^\/\\]+)/);
        if (match) {
          existingPages.add(match[1]);
        }
      }
    }
  } catch (error) {}
}

findExistingPages('src/app/vending-leads');

// Filter to only cities that don't exist
const newCities = moreCities.filter(city => !existingPages.has(city.slug));
console.log(`Found ${newCities.length} new cities from Texas list`);

// Combine with existing list
const combinedList = [...existingList, ...newCities];
const finalList = combinedList.slice(0, 500);

console.log(`\nTotal cities in final list: ${finalList.length} (target: 500)`);

// Save list
fs.writeFileSync('next_500_cities.json', JSON.stringify(finalList, null, 2));
console.log(`\nSaved ${finalList.length} cities to next_500_cities.json`);

