const fs = require('fs');
const path = require('path');

// Comprehensive list of additional cities to check
const additionalCitiesList = [
  // More California cities
  { name: 'Dublin', state: 'California', slug: 'dublin-california' },
  { name: 'El Cajon', state: 'California', slug: 'el-cajon-california' },
  { name: 'El Centro', state: 'California', slug: 'el-centro-california' },
  { name: 'El Monte', state: 'California', slug: 'el-monte-california' },
  { name: 'Elk Grove', state: 'California', slug: 'elk-grove-california' },
  { name: 'Emeryville', state: 'California', slug: 'emeryville-california' },
  { name: 'Encinitas', state: 'California', slug: 'encinitas-california' },
  { name: 'Escondido', state: 'California', slug: 'escondido-california' },
  { name: 'Fairfield', state: 'California', slug: 'fairfield-california' },
  { name: 'Folsom', state: 'California', slug: 'folsom-california' },
  { name: 'Fontana', state: 'California', slug: 'fontana-california' },
  { name: 'Foster City', state: 'California', slug: 'foster-city-california' },
  { name: 'Fremont', state: 'California', slug: 'fremont-california' },
  { name: 'Fresno', state: 'California', slug: 'fresno-california' },
  { name: 'Fullerton', state: 'California', slug: 'fullerton-california' },
  { name: 'Garden Grove', state: 'California', slug: 'garden-grove-california' },
  { name: 'Gardena', state: 'California', slug: 'gardena-california' },
  { name: 'Gilroy', state: 'California', slug: 'gilroy-california' },
  { name: 'Glendora', state: 'California', slug: 'glendora-california' },
  { name: 'Goleta', state: 'California', slug: 'goleta-california' },
  { name: 'Hawthorne', state: 'California', slug: 'hawthorne-california' },
  { name: 'Hayward', state: 'California', slug: 'hayward-california' },
  { name: 'Hemet', state: 'California', slug: 'hemet-california' },
  { name: 'Hesperia', state: 'California', slug: 'hesperia-california' },
  { name: 'Huntington Park', state: 'California', slug: 'huntington-park-california' },
  { name: 'Indio', state: 'California', slug: 'indio-california' },
  { name: 'Inglewood', state: 'California', slug: 'inglewood-california' },
  { name: 'Irvine', state: 'California', slug: 'irvine-california' },
  
  // More Texas cities
  { name: 'Harlingen', state: 'Texas', slug: 'harlingen-texas' },
  { name: 'Henderson', state: 'Texas', slug: 'henderson-texas' },
  { name: 'Hewitt', state: 'Texas', slug: 'hewitt-texas' },
  { name: 'Hidalgo', state: 'Texas', slug: 'hidalgo-texas' },
  { name: 'Highland Village', state: 'Texas', slug: 'highland-village-texas' },
  { name: 'Hillsboro', state: 'Texas', slug: 'hillsboro-texas' },
  { name: 'Harlingen', state: 'Texas', slug: 'harlingen-texas' },
  { name: 'Mesquite', state: 'Texas', slug: 'mesquite-texas' },
  { name: 'Midland', state: 'Texas', slug: 'midland-texas' },
  { name: 'Missouri City', state: 'Texas', slug: 'missouri-city-texas' },
  { name: 'Mount Pleasant', state: 'Texas', slug: 'mount-pleasant-texas' },
  { name: 'Nacogdoches', state: 'Texas', slug: 'nacogdoches-texas' },
  { name: 'New Braunfels', state: 'Texas', slug: 'new-braunfels-texas' },
  { name: 'North Richland Hills', state: 'Texas', slug: 'north-richland-hills-texas' },
  { name: 'Odessa', state: 'Texas', slug: 'odessa-texas' },
  { name: 'Orange', state: 'Texas', slug: 'orange-texas' },
  { name: 'Palestine', state: 'Texas', slug: 'palestine-texas' },
  { name: 'Pasadena', state: 'Texas', slug: 'pasadena-texas' },
  { name: 'Pearland', state: 'Texas', slug: 'pearland-texas' },
  { name: 'Pflugerville', state: 'Texas', slug: 'pflugerville-texas' },
  { name: 'Pharr', state: 'Texas', slug: 'pharr-texas' },
  { name: 'Plainview', state: 'Texas', slug: 'plainview-texas' },
  { name: 'Plano', state: 'Texas', slug: 'plano-texas' },
  { name: 'Port Arthur', state: 'Texas', slug: 'port-arthur-texas' },
  { name: 'Port Lavaca', state: 'Texas', slug: 'port-lavaca-texas' },
  { name: 'Richardson', state: 'Texas', slug: 'richardson-texas' },
  { name: 'Rockwall', state: 'Texas', slug: 'rockwall-texas' },
  { name: 'Rosenberg', state: 'Texas', slug: 'rosenberg-texas' },
  { name: 'Round Rock', state: 'Texas', slug: 'round-rock-texas' },
  { name: 'Rowlett', state: 'Texas', slug: 'rowlett-texas' },
  { name: 'San Angelo', state: 'Texas', slug: 'san-angelo-texas' },
  { name: 'San Antonio', state: 'Texas', slug: 'san-antonio-texas' },
  { name: 'San Marcos', state: 'Texas', slug: 'san-marcos-texas' },
  { name: 'Schertz', state: 'Texas', slug: 'schertz-texas' },
  { name: 'Seagoville', state: 'Texas', slug: 'seagoville-texas' },
  { name: 'Seguin', state: 'Texas', slug: 'seguin-texas' },
  { name: 'Sherman', state: 'Texas', slug: 'sherman-texas' },
  { name: 'Snyder', state: 'Texas', slug: 'snyder-texas' },
  { name: 'Southlake', state: 'Texas', slug: 'southlake-texas' },
  { name: 'Sugar Land', state: 'Texas', slug: 'sugar-land-texas' },
  { name: 'Temple', state: 'Texas', slug: 'temple-texas' },
  { name: 'Terrell', state: 'Texas', slug: 'terrell-texas' },
  { name: 'Texarkana', state: 'Texas', slug: 'texarkana-texas' },
  { name: 'Texas City', state: 'Texas', slug: 'texas-city-texas' },
  { name: 'The Colony', state: 'Texas', slug: 'the-colony-texas' },
  { name: 'Tomball', state: 'Texas', slug: 'tomball-texas' },
  { name: 'Tyler', state: 'Texas', slug: 'tyler-texas' },
  { name: 'Universal City', state: 'Texas', slug: 'universal-city-texas' },
  { name: 'Victoria', state: 'Texas', slug: 'victoria-texas' },
  { name: 'Waco', state: 'Texas', slug: 'waco-texas' },
  { name: 'Waxahachie', state: 'Texas', slug: 'waxahachie-texas' },
  { name: 'Weatherford', state: 'Texas', slug: 'weatherford-texas' },
  { name: 'Weslaco', state: 'Texas', slug: 'weslaco-texas' },
  { name: 'Wichita Falls', state: 'Texas', slug: 'wichita-falls-texas' },
  { name: 'Willis', state: 'Texas', slug: 'willis-texas' },
  { name: 'Woodway', state: 'Texas', slug: 'woodway-texas' },
  
  // More Florida cities
  { name: 'Melbourne', state: 'Florida', slug: 'melbourne-florida' },
  { name: 'Merritt Island', state: 'Florida', slug: 'merritt-island-florida' },
  { name: 'Miami Beach', state: 'Florida', slug: 'miami-beach-florida' },
  { name: 'Miami Gardens', state: 'Florida', slug: 'miami-gardens-florida' },
  { name: 'Milton', state: 'Florida', slug: 'milton-florida' },
  { name: 'Minneola', state: 'Florida', slug: 'minneola-florida' },
  { name: 'Mount Dora', state: 'Florida', slug: 'mount-dora-florida' },
  { name: 'Naples', state: 'Florida', slug: 'naples-florida' },
  { name: 'New Port Richey', state: 'Florida', slug: 'new-port-richey-florida' },
  { name: 'New Smyrna Beach', state: 'Florida', slug: 'new-smyrna-beach-florida' },
  { name: 'Niceville', state: 'Florida', slug: 'niceville-florida' },
  { name: 'North Miami', state: 'Florida', slug: 'north-miami-florida' },
  { name: 'North Port', state: 'Florida', slug: 'north-port-florida' },
  { name: 'Ocala', state: 'Florida', slug: 'ocala-florida' },
  { name: 'Ocoee', state: 'Florida', slug: 'ocoee-florida' },
  { name: 'Orange Park', state: 'Florida', slug: 'orange-park-florida' },
  { name: 'Orlando', state: 'Florida', slug: 'orlando-florida' },
  { name: 'Ormond Beach', state: 'Florida', slug: 'ormond-beach-florida' },
  { name: 'Oviedo', state: 'Florida', slug: 'oviedo-florida' },
  { name: 'Palm Bay', state: 'Florida', slug: 'palm-bay-florida' },
  { name: 'Palm Beach Gardens', state: 'Florida', slug: 'palm-beach-gardens-florida' },
  { name: 'Palm Coast', state: 'Florida', slug: 'palm-coast-florida' },
  { name: 'Palmetto Bay', state: 'Florida', slug: 'palmetto-bay-florida' },
  { name: 'Panama City', state: 'Florida', slug: 'panama-city-florida' },
  { name: 'Panama City Beach', state: 'Florida', slug: 'panama-city-beach-florida' },
  { name: 'Pembroke Pines', state: 'Florida', slug: 'pembroke-pines-florida' },
  { name: 'Pensacola', state: 'Florida', slug: 'pensacola-florida' },
  { name: 'Plant City', state: 'Florida', slug: 'plant-city-florida' },
  { name: 'Pompano Beach', state: 'Florida', slug: 'pompano-beach-florida' },
  { name: 'Port Charlotte', state: 'Florida', slug: 'port-charlotte-florida' },
  { name: 'Port Orange', state: 'Florida', slug: 'port-orange-florida' },
  { name: 'Port St. Lucie', state: 'Florida', slug: 'port-st-lucie-florida' },
  { name: 'Punta Gorda', state: 'Florida', slug: 'punta-gorda-florida' },
  { name: 'Riviera Beach', state: 'Florida', slug: 'riviera-beach-florida' },
  { name: 'Rockledge', state: 'Florida', slug: 'rockledge-florida' },
  { name: 'Royal Palm Beach', state: 'Florida', slug: 'royal-palm-beach-florida' },
  { name: 'Sanford', state: 'Florida', slug: 'sanford-florida' },
  { name: 'Sarasota', state: 'Florida', slug: 'sarasota-florida' },
  { name: 'Satellite Beach', state: 'Florida', slug: 'satellite-beach-florida' },
  { name: 'Sebastian', state: 'Florida', slug: 'sebastian-florida' },
  { name: 'Sebring', state: 'Florida', slug: 'sebring-florida' },
  { name: 'Seminole', state: 'Florida', slug: 'seminole-florida' },
  { name: 'St. Augustine', state: 'Florida', slug: 'st-augustine-florida' },
  { name: 'St. Cloud', state: 'Florida', slug: 'st-cloud-florida' },
  { name: 'St. Petersburg', state: 'Florida', slug: 'st-petersburg-florida' },
  { name: 'Stuart', state: 'Florida', slug: 'stuart-florida' },
  { name: 'Sunrise', state: 'Florida', slug: 'sunrise-florida' },
  { name: 'Tallahassee', state: 'Florida', slug: 'tallahassee-florida' },
  { name: 'Tampa', state: 'Florida', slug: 'tampa-florida' },
  { name: 'Tarpon Springs', state: 'Florida', slug: 'tarpon-springs-florida' },
  { name: 'Tavares', state: 'Florida', slug: 'tavares-florida' },
  { name: 'Titusville', state: 'Florida', slug: 'titusville-florida' },
  { name: 'Venice', state: 'Florida', slug: 'venice-florida' },
  { name: 'Vero Beach', state: 'Florida', slug: 'vero-beach-florida' },
  { name: 'Wellington', state: 'Florida', slug: 'wellington-florida' },
  { name: 'West Palm Beach', state: 'Florida', slug: 'west-palm-beach-florida' },
  { name: 'Winter Garden', state: 'Florida', slug: 'winter-garden-florida' },
  { name: 'Winter Haven', state: 'Florida', slug: 'winter-haven-florida' },
  { name: 'Winter Park', state: 'Florida', slug: 'winter-park-florida' },
  { name: 'Winter Springs', state: 'Florida', slug: 'winter-springs-florida' },
  { name: 'Zephyrhills', state: 'Florida', slug: 'zephyrhills-florida' },
  
  // More states - New York
  { name: 'Albany', state: 'New York', slug: 'albany-new-york' },
  { name: 'Amherst', state: 'New York', slug: 'amherst-new-york' },
  { name: 'Auburn', state: 'New York', slug: 'auburn-new-york' },
  { name: 'Batavia', state: 'New York', slug: 'batavia-new-york' },
  { name: 'Binghamton', state: 'New York', slug: 'binghamton-new-york' },
  { name: 'Buffalo', state: 'New York', slug: 'buffalo-new-york' },
  { name: 'Canandaigua', state: 'New York', slug: 'canandaigua-new-york' },
  { name: 'Cortland', state: 'New York', slug: 'cortland-new-york' },
  { name: 'Elmira', state: 'New York', slug: 'elmira-new-york' },
  { name: 'Geneva', state: 'New York', slug: 'geneva-new-york' },
  { name: 'Glens Falls', state: 'New York', slug: 'glens-falls-new-york' },
  { name: 'Gloversville', state: 'New York', slug: 'gloversville-new-york' },
  { name: 'Hornell', state: 'New York', slug: 'hornell-new-york' },
  { name: 'Ithaca', state: 'New York', slug: 'ithaca-new-york' },
  { name: 'Jamestown', state: 'New York', slug: 'jamestown-new-york' },
  { name: 'Kingston', state: 'New York', slug: 'kingston-new-york' },
  { name: 'Lockport', state: 'New York', slug: 'lockport-new-york' },
  { name: 'Mount Vernon', state: 'New York', slug: 'mount-vernon-new-york' },
  { name: 'New Rochelle', state: 'New York', slug: 'new-rochelle-new-york' },
  { name: 'Newburgh', state: 'New York', slug: 'newburgh-new-york' },
  { name: 'Niagara Falls', state: 'New York', slug: 'niagara-falls-new-york' },
  { name: 'Ogdensburg', state: 'New York', slug: 'ogdensburg-new-york' },
  { name: 'Olean', state: 'New York', slug: 'olean-new-york' },
  { name: 'Oneonta', state: 'New York', slug: 'oneonta-new-york' },
  { name: 'Oswego', state: 'New York', slug: 'oswego-new-york' },
  { name: 'Peekskill', state: 'New York', slug: 'peekskill-new-york' },
  { name: 'Plattsburgh', state: 'New York', slug: 'plattsburgh-new-york' },
  { name: 'Poughkeepsie', state: 'New York', slug: 'poughkeepsie-new-york' },
  { name: 'Rochester', state: 'New York', slug: 'rochester-new-york' },
  { name: 'Rome', state: 'New York', slug: 'rome-new-york' },
  { name: 'Saratoga Springs', state: 'New York', slug: 'saratoga-springs-new-york' },
  { name: 'Schenectady', state: 'New York', slug: 'schenectady-new-york' },
  { name: 'Syracuse', state: 'New York', slug: 'syracuse-new-york' },
  { name: 'Tonawanda', state: 'New York', slug: 'tonawanda-new-york' },
  { name: 'Troy', state: 'New York', slug: 'troy-new-york' },
  { name: 'Utica', state: 'New York', slug: 'utica-new-york' },
  { name: 'Watertown', state: 'New York', slug: 'watertown-new-york' },
  { name: 'White Plains', state: 'New York', slug: 'white-plains-new-york' },
  { name: 'Yonkers', state: 'New York', slug: 'yonkers-new-york' },
  
  // More states - North Carolina
  { name: 'Asheville', state: 'North Carolina', slug: 'asheville-north-carolina' },
  { name: 'Burlington', state: 'North Carolina', slug: 'burlington-north-carolina' },
  { name: 'Cary', state: 'North Carolina', slug: 'cary-north-carolina' },
  { name: 'Chapel Hill', state: 'North Carolina', slug: 'chapel-hill-north-carolina' },
  { name: 'Charlotte', state: 'North Carolina', slug: 'charlotte-north-carolina' },
  { name: 'Concord', state: 'North Carolina', slug: 'concord-north-carolina' },
  { name: 'Durham', state: 'North Carolina', slug: 'durham-north-carolina' },
  { name: 'Fayetteville', state: 'North Carolina', slug: 'fayetteville-north-carolina' },
  { name: 'Gastonia', state: 'North Carolina', slug: 'gastonia-north-carolina' },
  { name: 'Goldsboro', state: 'North Carolina', slug: 'goldsboro-north-carolina' },
  { name: 'Greensboro', state: 'North Carolina', slug: 'greensboro-north-carolina' },
  { name: 'Greenville', state: 'North Carolina', slug: 'greenville-north-carolina' },
  { name: 'Hickory', state: 'North Carolina', slug: 'hickory-north-carolina' },
  { name: 'High Point', state: 'North Carolina', slug: 'high-point-north-carolina' },
  { name: 'Jacksonville', state: 'North Carolina', slug: 'jacksonville-north-carolina' },
  { name: 'Kannapolis', state: 'North Carolina', slug: 'kannapolis-north-carolina' },
  { name: 'Lumberton', state: 'North Carolina', slug: 'lumberton-north-carolina' },
  { name: 'Monroe', state: 'North Carolina', slug: 'monroe-north-carolina' },
  { name: 'Raleigh', state: 'North Carolina', slug: 'raleigh-north-carolina' },
  { name: 'Rocky Mount', state: 'North Carolina', slug: 'rocky-mount-north-carolina' },
  { name: 'Salisbury', state: 'North Carolina', slug: 'salisbury-north-carolina' },
  { name: 'Shelby', state: 'North Carolina', slug: 'shelby-north-carolina' },
  { name: 'Statesville', state: 'North Carolina', slug: 'statesville-north-carolina' },
  { name: 'Thomasville', state: 'North Carolina', slug: 'thomasville-north-carolina' },
  { name: 'Wilmington', state: 'North Carolina', slug: 'wilmington-north-carolina' },
  { name: 'Wilson', state: 'North Carolina', slug: 'wilson-north-carolina' },
  { name: 'Winston-Salem', state: 'North Carolina', slug: 'winston-salem-north-carolina' },
  
  // More states - Georgia
  { name: 'Albany', state: 'Georgia', slug: 'albany-georgia' },
  { name: 'Alpharetta', state: 'Georgia', slug: 'alpharetta-georgia' },
  { name: 'Americus', state: 'Georgia', slug: 'americus-georgia' },
  { name: 'Athens', state: 'Georgia', slug: 'athens-georgia' },
  { name: 'Atlanta', state: 'Georgia', slug: 'atlanta-georgia' },
  { name: 'Augusta', state: 'Georgia', slug: 'augusta-georgia' },
  { name: 'Brunswick', state: 'Georgia', slug: 'brunswick-georgia' },
  { name: 'Carrollton', state: 'Georgia', slug: 'carrollton-georgia' },
  { name: 'Columbus', state: 'Georgia', slug: 'columbus-georgia' },
  { name: 'Dalton', state: 'Georgia', slug: 'dalton-georgia' },
  { name: 'Decatur', state: 'Georgia', slug: 'decatur-georgia' },
  { name: 'Douglas', state: 'Georgia', slug: 'douglas-georgia' },
  { name: 'Dublin', state: 'Georgia', slug: 'dublin-georgia' },
  { name: 'Gainesville', state: 'Georgia', slug: 'gainesville-georgia' },
  { name: 'Griffin', state: 'Georgia', slug: 'griffin-georgia' },
  { name: 'LaGrange', state: 'Georgia', slug: 'lagrange-georgia' },
  { name: 'Macon', state: 'Georgia', slug: 'macon-georgia' },
  { name: 'Marietta', state: 'Georgia', slug: 'marietta-georgia' },
  { name: 'Milledgeville', state: 'Georgia', slug: 'milledgeville-georgia' },
  { name: 'Newnan', state: 'Georgia', slug: 'newnan-georgia' },
  { name: 'Rome', state: 'Georgia', slug: 'rome-georgia' },
  { name: 'Roswell', state: 'Georgia', slug: 'roswell-georgia' },
  { name: 'Savannah', state: 'Georgia', slug: 'savannah-georgia' },
  { name: 'Smyrna', state: 'Georgia', slug: 'smyrna-georgia' },
  { name: 'Statesboro', state: 'Georgia', slug: 'statesboro-georgia' },
  { name: 'Thomasville', state: 'Georgia', slug: 'thomasville-georgia' },
  { name: 'Valdosta', state: 'Georgia', slug: 'valdosta-georgia' },
  { name: 'Warner Robins', state: 'Georgia', slug: 'warner-robins-georgia' },
  { name: 'Waycross', state: 'Georgia', slug: 'waycross-georgia' },
  
  // More states - Arizona
  { name: 'Apache Junction', state: 'Arizona', slug: 'apache-junction-arizona' },
  { name: 'Avondale', state: 'Arizona', slug: 'avondale-arizona' },
  { name: 'Buckeye', state: 'Arizona', slug: 'buckeye-arizona' },
  { name: 'Bullhead City', state: 'Arizona', slug: 'bullhead-city-arizona' },
  { name: 'Casa Grande', state: 'Arizona', slug: 'casa-grande-arizona' },
  { name: 'Chandler', state: 'Arizona', slug: 'chandler-arizona' },
  { name: 'Chino Valley', state: 'Arizona', slug: 'chino-valley-arizona' },
  { name: 'Coolidge', state: 'Arizona', slug: 'coolidge-arizona' },
  { name: 'Cottonwood', state: 'Arizona', slug: 'cottonwood-arizona' },
  { name: 'Douglas', state: 'Arizona', slug: 'douglas-arizona' },
  { name: 'Flagstaff', state: 'Arizona', slug: 'flagstaff-arizona' },
  { name: 'Florence', state: 'Arizona', slug: 'florence-arizona' },
  { name: 'Gilbert', state: 'Arizona', slug: 'gilbert-arizona' },
  { name: 'Glendale', state: 'Arizona', slug: 'glendale-arizona' },
  { name: 'Goodyear', state: 'Arizona', slug: 'goodyear-arizona' },
  { name: 'Kingman', state: 'Arizona', slug: 'kingman-arizona' },
  { name: 'Lake Havasu City', state: 'Arizona', slug: 'lake-havasu-city-arizona' },
  { name: 'Maricopa', state: 'Arizona', slug: 'maricopa-arizona' },
  { name: 'Mesa', state: 'Arizona', slug: 'mesa-arizona' },
  { name: 'Nogales', state: 'Arizona', slug: 'nogales-arizona' },
  { name: 'Oro Valley', state: 'Arizona', slug: 'oro-valley-arizona' },
  { name: 'Payson', state: 'Arizona', slug: 'payson-arizona' },
  { name: 'Peoria', state: 'Arizona', slug: 'peoria-arizona' },
  { name: 'Phoenix', state: 'Arizona', slug: 'phoenix-arizona' },
  { name: 'Prescott', state: 'Arizona', slug: 'prescott-arizona' },
  { name: 'Prescott Valley', state: 'Arizona', slug: 'prescott-valley-arizona' },
  { name: 'Queen Creek', state: 'Arizona', slug: 'queen-creek-arizona' },
  { name: 'Safford', state: 'Arizona', slug: 'safford-arizona' },
  { name: 'San Luis', state: 'Arizona', slug: 'san-luis-arizona' },
  { name: 'Scottsdale', state: 'Arizona', slug: 'scottsdale-arizona' },
  { name: 'Sierra Vista', state: 'Arizona', slug: 'sierra-vista-arizona' },
  { name: 'Surprise', state: 'Arizona', slug: 'surprise-arizona' },
  { name: 'Tempe', state: 'Arizona', slug: 'tempe-arizona' },
  { name: 'Tucson', state: 'Arizona', slug: 'tucson-arizona' },
  { name: 'Yuma', state: 'Arizona', slug: 'yuma-arizona' },
  
  // More states - Colorado
  { name: 'Arvada', state: 'Colorado', slug: 'arvada-colorado' },
  { name: 'Aspen', state: 'Colorado', slug: 'aspen-colorado' },
  { name: 'Aurora', state: 'Colorado', slug: 'aurora-colorado' },
  { name: 'Boulder', state: 'Colorado', slug: 'boulder-colorado' },
  { name: 'Broomfield', state: 'Colorado', slug: 'broomfield-colorado' },
  { name: 'Castle Rock', state: 'Colorado', slug: 'castle-rock-colorado' },
  { name: 'Colorado Springs', state: 'Colorado', slug: 'colorado-springs-colorado' },
  { name: 'Commerce City', state: 'Colorado', slug: 'commerce-city-colorado' },
  { name: 'Denver', state: 'Colorado', slug: 'denver-colorado' },
  { name: 'Durango', state: 'Colorado', slug: 'durango-colorado' },
  { name: 'Englewood', state: 'Colorado', slug: 'englewood-colorado' },
  { name: 'Fort Collins', state: 'Colorado', slug: 'fort-collins-colorado' },
  { name: 'Glenwood Springs', state: 'Colorado', slug: 'glenwood-springs-colorado' },
  { name: 'Grand Junction', state: 'Colorado', slug: 'grand-junction-colorado' },
  { name: 'Greeley', state: 'Colorado', slug: 'greeley-colorado' },
  { name: 'Lakewood', state: 'Colorado', slug: 'lakewood-colorado' },
  { name: 'Littleton', state: 'Colorado', slug: 'littleton-colorado' },
  { name: 'Loveland', state: 'Colorado', slug: 'loveland-colorado' },
  { name: 'Montrose', state: 'Colorado', slug: 'montrose-colorado' },
  { name: 'Parker', state: 'Colorado', slug: 'parker-colorado' },
  { name: 'Pueblo', state: 'Colorado', slug: 'pueblo-colorado' },
  { name: 'Thornton', state: 'Colorado', slug: 'thornton-colorado' },
  { name: 'Westminster', state: 'Colorado', slug: 'westminster-colorado' },
  
  // More states - Nevada
  { name: 'Boulder City', state: 'Nevada', slug: 'boulder-city-nevada' },
  { name: 'Carson City', state: 'Nevada', slug: 'carson-city-nevada' },
  { name: 'Elko', state: 'Nevada', slug: 'elko-nevada' },
  { name: 'Henderson', state: 'Nevada', slug: 'henderson-nevada' },
  { name: 'Las Vegas', state: 'Nevada', slug: 'las-vegas-nevada' },
  { name: 'Mesquite', state: 'Nevada', slug: 'mesquite-nevada' },
  { name: 'North Las Vegas', state: 'Nevada', slug: 'north-las-vegas-nevada' },
  { name: 'Reno', state: 'Nevada', slug: 'reno-nevada' },
  { name: 'Sparks', state: 'Nevada', slug: 'sparks-nevada' },
  { name: 'Winnemucca', state: 'Nevada', slug: 'winnemucca-nevada' },
  
  // More states - Oregon
  { name: 'Albany', state: 'Oregon', slug: 'albany-oregon' },
  { name: 'Ashland', state: 'Oregon', slug: 'ashland-oregon' },
  { name: 'Beaverton', state: 'Oregon', slug: 'beaverton-oregon' },
  { name: 'Bend', state: 'Oregon', slug: 'bend-oregon' },
  { name: 'Corvallis', state: 'Oregon', slug: 'corvallis-oregon' },
  { name: 'Eugene', state: 'Oregon', slug: 'eugene-oregon' },
  { name: 'Gresham', state: 'Oregon', slug: 'gresham-oregon' },
  { name: 'Hillsboro', state: 'Oregon', slug: 'hillsboro-oregon' },
  { name: 'Klamath Falls', state: 'Oregon', slug: 'klamath-falls-oregon' },
  { name: 'Medford', state: 'Oregon', slug: 'medford-oregon' },
  { name: 'Oregon City', state: 'Oregon', slug: 'oregon-city-oregon' },
  { name: 'Portland', state: 'Oregon', slug: 'portland-oregon' },
  { name: 'Roseburg', state: 'Oregon', slug: 'roseburg-oregon' },
  { name: 'Salem', state: 'Oregon', slug: 'salem-oregon' },
  { name: 'Springfield', state: 'Oregon', slug: 'springfield-oregon' },
  { name: 'The Dalles', state: 'Oregon', slug: 'the-dalles-oregon' },
  { name: 'Tigard', state: 'Oregon', slug: 'tigard-oregon' },
  
  // More states - Washington
  { name: 'Aberdeen', state: 'Washington', slug: 'aberdeen-washington' },
  { name: 'Anacortes', state: 'Washington', slug: 'anacortes-washington' },
  { name: 'Auburn', state: 'Washington', slug: 'auburn-washington' },
  { name: 'Bellingham', state: 'Washington', slug: 'bellingham-washington' },
  { name: 'Bothell', state: 'Washington', slug: 'bothell-washington' },
  { name: 'Bremerton', state: 'Washington', slug: 'bremerton-washington' },
  { name: 'Burien', state: 'Washington', slug: 'burien-washington' },
  { name: 'Centralia', state: 'Washington', slug: 'centralia-washington' },
  { name: 'Cheney', state: 'Washington', slug: 'cheney-washington' },
  { name: 'Des Moines', state: 'Washington', slug: 'des-moines-washington' },
  { name: 'Edmonds', state: 'Washington', slug: 'edmonds-washington' },
  { name: 'Ellensburg', state: 'Washington', slug: 'ellensburg-washington' },
  { name: 'Enumclaw', state: 'Washington', slug: 'enumclaw-washington' },
  { name: 'Everett', state: 'Washington', slug: 'everett-washington' },
  { name: 'Federal Way', state: 'Washington', slug: 'federal-way-washington' },
  { name: 'Issaquah', state: 'Washington', slug: 'issaquah-washington' },
  { name: 'Kennewick', state: 'Washington', slug: 'kennewick-washington' },
  { name: 'Kent', state: 'Washington', slug: 'kent-washington' },
  { name: 'Kirkland', state: 'Washington', slug: 'kirkland-washington' },
  { name: 'Lacey', state: 'Washington', slug: 'lacey-washington' },
  { name: 'Lakewood', state: 'Washington', slug: 'lakewood-washington' },
  { name: 'Longview', state: 'Washington', slug: 'longview-washington' },
  { name: 'Marysville', state: 'Washington', slug: 'marysville-washington' },
  { name: 'Mount Vernon', state: 'Washington', slug: 'mount-vernon-washington' },
  { name: 'Mukilteo', state: 'Washington', slug: 'mukilteo-washington' },
  { name: 'Oak Harbor', state: 'Washington', slug: 'oak-harbor-washington' },
  { name: 'Olympia', state: 'Washington', slug: 'olympia-washington' },
  { name: 'Pasco', state: 'Washington', slug: 'pasco-washington' },
  { name: 'Pullman', state: 'Washington', slug: 'pullman-washington' },
  { name: 'Puyallup', state: 'Washington', slug: 'puyallup-washington' },
  { name: 'Redmond', state: 'Washington', slug: 'redmond-washington' },
  { name: 'Renton', state: 'Washington', slug: 'renton-washington' },
  { name: 'Richland', state: 'Washington', slug: 'richland-washington' },
  { name: 'Sammamish', state: 'Washington', slug: 'sammamish-washington' },
  { name: 'Seattle', state: 'Washington', slug: 'seattle-washington' },
  { name: 'Shoreline', state: 'Washington', slug: 'shoreline-washington' },
  { name: 'Spokane', state: 'Washington', slug: 'spokane-washington' },
  { name: 'Spokane Valley', state: 'Washington', slug: 'spokane-valley-washington' },
  { name: 'Tacoma', state: 'Washington', slug: 'tacoma-washington' },
  { name: 'Tukwila', state: 'Washington', slug: 'tukwila-washington' },
  { name: 'Tumwater', state: 'Washington', slug: 'tumwater-washington' },
  { name: 'University Place', state: 'Washington', slug: 'university-place-washington' },
  { name: 'Vancouver', state: 'Washington', slug: 'vancouver-washington' },
  { name: 'Walla Walla', state: 'Washington', slug: 'walla-walla-washington' },
  { name: 'Wenatchee', state: 'Washington', slug: 'wenatchee-washington' },
  { name: 'Yakima', state: 'Washington', slug: 'yakima-washington' },
];

// Check existing pages
const existingPages = new Set();
function findExistingPages(dir) {
  try {
    const files = fs.readdirSync(dir);
    for (const file of files) {
      const fullPath = path.join(dir, file);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        findExistingPages(fullPath);
      } else if (file === 'pageClient.tsx') {
        const match = fullPath.match(/vending-leads[\/\\]([^\/\\]+)/);
        if (match) {
          existingPages.add(match[1]);
        }
      }
    }
  } catch (error) {}
}

findExistingPages('src/app/vending-leads');

// Filter to only cities that don't exist
const citiesToCreate = additionalCitiesList.filter(city => !existingPages.has(city.slug));
console.log(`Found ${citiesToCreate.length} cities to create from ${additionalCitiesList.length} total`);

if (citiesToCreate.length === 0) {
  console.log('\nAll cities already have pages!');
  process.exit(0);
}

// Take first 100
const finalCities = citiesToCreate.slice(0, 100);
console.log(`\nSelected ${finalCities.length} cities to create:`);
finalCities.forEach((city, idx) => {
  console.log(`${idx + 1}. ${city.name}, ${city.state} (${city.slug})`);
});

// Save list
fs.writeFileSync('next_100_cities.json', JSON.stringify(finalCities, null, 2));
console.log(`\nSaved ${finalCities.length} cities to next_100_cities.json`);


