const fs = require('fs');
const path = require('path');

// State abbreviations mapping
const stateAbbreviations = {
  'Alabama': 'AL',
  'Alaska': 'AK',
  'Arizona': 'AZ',
  'Arkansas': 'AR',
  'California': 'CA',
  'Colorado': 'CO',
  'Connecticut': 'CT',
  'Delaware': 'DE',
  'Florida': 'FL',
  'Georgia': 'GA',
  'Hawaii': 'HI',
  'Idaho': 'ID',
  'Illinois': 'IL',
  'Indiana': 'IN',
  'Iowa': 'IA',
  'Kansas': 'KS',
  'Kentucky': 'KY',
  'Louisiana': 'LA',
  'Maine': 'ME',
  'Maryland': 'MD',
  'Massachusetts': 'MA',
  'Michigan': 'MI',
  'Minnesota': 'MN',
  'Mississippi': 'MS',
  'Missouri': 'MO',
  'Montana': 'MT',
  'Nebraska': 'NE',
  'Nevada': 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  'Ohio': 'OH',
  'Oklahoma': 'OK',
  'Oregon': 'OR',
  'Pennsylvania': 'PA',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  'Tennessee': 'TN',
  'Texas': 'TX',
  'Utah': 'UT',
  'Vermont': 'VT',
  'Virginia': 'VA',
  'Washington': 'WA',
  'West Virginia': 'WV',
  'Wisconsin': 'WI',
  'Wyoming': 'WY',
  'Washington DC': 'DC',
  'District of Columbia': 'DC'
};

// Get the 100 new cities we just created
const newCities = [
  { name: 'Prattville', state: 'Alabama', slug: 'prattville-alabama' },
  { name: 'Opelika', state: 'Alabama', slug: 'opelika-alabama' },
  { name: 'Bessemer', state: 'Alabama', slug: 'bessemer-alabama' },
  { name: 'Gadsden', state: 'Alabama', slug: 'gadsden-alabama' },
  { name: 'Prichard', state: 'Alabama', slug: 'prichard-alabama' },
  { name: 'Avondale', state: 'Arizona', slug: 'avondale-arizona' },
  { name: 'Buckeye', state: 'Arizona', slug: 'buckeye-arizona' },
  { name: 'Casa Grande', state: 'Arizona', slug: 'casa-grande-arizona' },
  { name: 'Goodyear', state: 'Arizona', slug: 'goodyear-arizona' },
  { name: 'Maricopa', state: 'Arizona', slug: 'maricopa-arizona' },
  { name: 'Prescott', state: 'Arizona', slug: 'prescott-arizona' },
  { name: 'Yuma', state: 'Arizona', slug: 'yuma-arizona' },
  { name: 'Hot Springs', state: 'Arkansas', slug: 'hot-springs-arkansas' },
  { name: 'Texarkana', state: 'Arkansas', slug: 'texarkana-arkansas' },
  { name: 'Alameda', state: 'California', slug: 'alameda-california' },
  { name: 'Baldwin Park', state: 'California', slug: 'baldwin-park-california' },
  { name: 'Bellflower', state: 'California', slug: 'bellflower-california' },
  { name: 'Buena Park', state: 'California', slug: 'buena-park-california' },
  { name: 'Camarillo', state: 'California', slug: 'camarillo-california' },
  { name: 'Castro Valley', state: 'California', slug: 'castro-valley-california' },
  { name: 'Cerritos', state: 'California', slug: 'cerritos-california' },
  { name: 'Citrus Heights', state: 'California', slug: 'citrus-heights-california' },
  { name: 'Cupertino', state: 'California', slug: 'cupertino-california' },
  { name: 'Dublin', state: 'California', slug: 'dublin-california' },
  { name: 'Folsom', state: 'California', slug: 'folsom-california' },
  { name: 'Fountain Valley', state: 'California', slug: 'fountain-valley-california' },
  { name: 'Hemet', state: 'California', slug: 'hemet-california' },
  { name: 'Hesperia', state: 'California', slug: 'hesperia-california' },
  { name: 'Huntington Park', state: 'California', slug: 'huntington-park-california' },
  { name: 'Indio', state: 'California', slug: 'indio-california' },
  { name: 'La Habra', state: 'California', slug: 'la-habra-california' },
  { name: 'La Mesa', state: 'California', slug: 'la-mesa-california' },
  { name: 'La Mirada', state: 'California', slug: 'la-mirada-california' },
  { name: 'Laguna Niguel', state: 'California', slug: 'laguna-niguel-california' },
  { name: 'Lancaster', state: 'California', slug: 'lancaster-california' },
  { name: 'Lodi', state: 'California', slug: 'lodi-california' },
  { name: 'Lompoc', state: 'California', slug: 'lompoc-california' },
  { name: 'Lynwood', state: 'California', slug: 'lynwood-california' },
  { name: 'Menifee', state: 'California', slug: 'menifee-california' },
  { name: 'Mission Viejo', state: 'California', slug: 'mission-viejo-california' },
  { name: 'Monterey Park', state: 'California', slug: 'monterey-park-california' },
  { name: 'Mountain View', state: 'California', slug: 'mountain-view-california' },
  { name: 'Napa', state: 'California', slug: 'napa-california' },
  { name: 'Newport Beach', state: 'California', slug: 'newport-beach-california' },
  { name: 'Palo Alto', state: 'California', slug: 'palo-alto-california' },
  { name: 'Petaluma', state: 'California', slug: 'petaluma-california' },
  { name: 'Pico Rivera', state: 'California', slug: 'pico-rivera-california' },
  { name: 'Pittsburg', state: 'California', slug: 'pittsburg-california' },
  { name: 'Redondo Beach', state: 'California', slug: 'redondo-beach-california' },
  { name: 'San Leandro', state: 'California', slug: 'san-leandro-california' },
  { name: 'San Rafael', state: 'California', slug: 'san-rafael-california' },
  { name: 'San Ramon', state: 'California', slug: 'san-ramon-california' },
  { name: 'South Gate', state: 'California', slug: 'south-gate-california' },
  { name: 'Tracy', state: 'California', slug: 'tracy-california' },
  { name: 'Tulare', state: 'California', slug: 'tulare-california' },
  { name: 'Turlock', state: 'California', slug: 'turlock-california' },
  { name: 'Tustin', state: 'California', slug: 'tustin-california' },
  { name: 'Union City', state: 'California', slug: 'union-city-california' },
  { name: 'Upland', state: 'California', slug: 'upland-california' },
  { name: 'Watsonville', state: 'California', slug: 'watsonville-california' },
  { name: 'Westminster', state: 'California', slug: 'westminster-california' },
  { name: 'Broomfield', state: 'Colorado', slug: 'broomfield-colorado' },
  { name: 'Loveland', state: 'Colorado', slug: 'loveland-colorado' },
  { name: 'Bristol', state: 'Connecticut', slug: 'bristol-connecticut' },
  { name: 'Enfield', state: 'Connecticut', slug: 'enfield-connecticut' },
  { name: 'Meriden', state: 'Connecticut', slug: 'meriden-connecticut' },
  { name: 'Middletown', state: 'Connecticut', slug: 'middletown-connecticut' },
  { name: 'Milford', state: 'Connecticut', slug: 'milford-connecticut' },
  { name: 'West Hartford', state: 'Connecticut', slug: 'west-hartford-connecticut' },
  { name: 'Boynton Beach', state: 'Florida', slug: 'boynton-beach-florida' },
  { name: 'Bradenton', state: 'Florida', slug: 'bradenton-florida' },
  { name: 'Davie', state: 'Florida', slug: 'davie-florida' },
  { name: 'Deerfield Beach', state: 'Florida', slug: 'deerfield-beach-florida' },
  { name: 'Delray Beach', state: 'Florida', slug: 'delray-beach-florida' },
  { name: 'Fort Pierce', state: 'Florida', slug: 'fort-pierce-florida' },
  { name: 'Greenacres', state: 'Florida', slug: 'greenacres-florida' },
  { name: 'Homestead', state: 'Florida', slug: 'homestead-florida' },
  { name: 'Jupiter', state: 'Florida', slug: 'jupiter-florida' },
  { name: 'Largo', state: 'Florida', slug: 'largo-florida' },
  { name: 'Margate', state: 'Florida', slug: 'margate-florida' },
  { name: 'Melbourne', state: 'Florida', slug: 'melbourne-florida' },
  { name: 'North Miami', state: 'Florida', slug: 'north-miami-florida' },
  { name: 'Ocala', state: 'Florida', slug: 'ocala-florida' },
  { name: 'Plantation', state: 'Florida', slug: 'plantation-florida' },
  { name: 'Port Charlotte', state: 'Florida', slug: 'port-charlotte-florida' },
  { name: 'Sanford', state: 'Florida', slug: 'sanford-florida' },
  { name: 'Sebastian', state: 'Florida', slug: 'sebastian-florida' },
  { name: 'Stuart', state: 'Florida', slug: 'stuart-florida' },
  { name: 'Sunrise', state: 'Florida', slug: 'sunrise-florida' },
  { name: 'Tamarac', state: 'Florida', slug: 'tamarac-florida' },
  { name: 'Titusville', state: 'Florida', slug: 'titusville-florida' },
  { name: 'Wellington', state: 'Florida', slug: 'wellington-florida' },
  { name: 'Weston', state: 'Florida', slug: 'weston-florida' },
  { name: 'Alpharetta', state: 'Georgia', slug: 'alpharetta-georgia' },
  { name: 'Carrollton', state: 'Georgia', slug: 'carrollton-georgia' },
  { name: 'Dalton', state: 'Georgia', slug: 'dalton-georgia' },
  { name: 'Douglasville', state: 'Georgia', slug: 'douglasville-georgia' },
  { name: 'Gainesville', state: 'Georgia', slug: 'gainesville-georgia' },
  { name: 'Johns Creek', state: 'Georgia', slug: 'johns-creek-georgia' },
  { name: 'Kennesaw', state: 'Georgia', slug: 'kennesaw-georgia' }
];

const baseDir = path.join(__dirname, '../src/app/how-to-start-a-vending-machine-business');
let fixedCount = 0;

newCities.forEach(city => {
  const pageFile = path.join(baseDir, city.slug, 'page.tsx');
  if (fs.existsSync(pageFile)) {
    let content = fs.readFileSync(pageFile, 'utf8');
    const stateAbbr = stateAbbreviations[city.state] || city.state;
    
    // Fix state abbreviation issues
    content = content.replace(/, A\b/g, `, ${stateAbbr}`);
    content = content.replace(/, A"/g, `, ${stateAbbr}"`);
    content = content.replace(/, A'/g, `, ${stateAbbr}'`);
    
    fs.writeFileSync(pageFile, content);
    fixedCount++;
  }
});

console.log(`Fixed ${fixedCount} files`);

