const fs = require('fs');
const path = require('path');

// Read existing cities to avoid duplicates
const existingCitiesFile = path.join(__dirname, '..', 'existing_cities.txt');
let existingCities = new Set();
if (fs.existsSync(existingCitiesFile)) {
  const existing = fs.readFileSync(existingCitiesFile, 'utf8').split('\n').map(c => c.trim()).filter(c => c);
  existingCities = new Set(existing);
}

// Comprehensive list of 500+ US cities across all states
const citiesToCreate = [
  // Additional Alabama cities
  { name: 'Phenix City', slug: 'phenix-city-alabama', state: 'Alabama' },
  { name: 'Sheffield', slug: 'sheffield-alabama', state: 'Alabama' },
  { name: 'Sylacauga', slug: 'sylacauga-alabama', state: 'Alabama' },
  { name: 'Talladega', slug: 'talladega-alabama', state: 'Alabama' },
  { name: 'Troy', slug: 'troy-alabama', state: 'Alabama' },
  
  // Additional Alaska cities
  { name: 'Unalaska', slug: 'unalaska-alaska', state: 'Alaska' },
  { name: 'Valdez', slug: 'valdez-alaska', state: 'Alaska' },
  
  // Additional Arizona cities
  { name: 'Sedona', slug: 'sedona-arizona', state: 'Arizona' },
  { name: 'Show Low', slug: 'show-low-arizona', state: 'Arizona' },
  
  // Additional Arkansas cities
  { name: 'Fayetteville', slug: 'fayetteville-arkansas', state: 'Arkansas' },
  { name: 'Fort Smith', slug: 'fort-smith-arkansas', state: 'Arkansas' },
  { name: 'Jonesboro', slug: 'jonesboro-arkansas', state: 'Arkansas' },
  { name: 'North Little Rock', slug: 'north-little-rock-arkansas', state: 'Arkansas' },
  { name: 'Paragould', slug: 'paragould-arkansas', state: 'Arkansas' },
  { name: 'Pine Bluff', slug: 'pine-bluff-arkansas', state: 'Arkansas' },
  { name: 'Rogers', slug: 'rogers-arkansas', state: 'Arkansas' },
  { name: 'Searcy', slug: 'searcy-arkansas', state: 'Arkansas' },
  { name: 'Springdale', slug: 'springdale-arkansas', state: 'Arkansas' },
  { name: 'Texarkana', slug: 'texarkana-arkansas', state: 'Arkansas' },
  { name: 'West Memphis', slug: 'west-memphis-arkansas', state: 'Arkansas' },
  
  // Additional California cities
  { name: 'Adelanto', slug: 'adelanto-california', state: 'California' },
  { name: 'Agoura Hills', slug: 'agoura-hills-california', state: 'California' },
  { name: 'Alhambra', slug: 'alhambra-california', state: 'California' },
  { name: 'Aliso Viejo', slug: 'aliso-viejo-california', state: 'California' },
  { name: 'Altadena', slug: 'altadena-california', state: 'California' },
  { name: 'Apple Valley', slug: 'apple-valley-california', state: 'California' },
  { name: 'Arroyo Grande', slug: 'arroyo-grande-california', state: 'California' },
  { name: 'Arvin', slug: 'arvin-california', state: 'California' },
  { name: 'Atascadero', slug: 'atascadero-california', state: 'California' },
  { name: 'Atherton', slug: 'atherton-california', state: 'California' },
  { name: 'Atwater', slug: 'atwater-california', state: 'California' },
  { name: 'Azusa', slug: 'azusa-california', state: 'California' },
  { name: 'Baldwin Park', slug: 'baldwin-park-california', state: 'California' },
  { name: 'Banning', slug: 'banning-california', state: 'California' },
  { name: 'Barstow', slug: 'barstow-california', state: 'California' },
  { name: 'Beaumont', slug: 'beaumont-california', state: 'California' },
  { name: 'Bell', slug: 'bell-california', state: 'California' },
  { name: 'Bell Gardens', slug: 'bell-gardens-california', state: 'California' },
  { name: 'Bellflower', slug: 'bellflower-california', state: 'California' },
  { name: 'Belmont', slug: 'belmont-california', state: 'California' },
  { name: 'Benicia', slug: 'benicia-california', state: 'California' },
  { name: 'Berkeley', slug: 'berkeley-california', state: 'California' },
  { name: 'Beverly Hills', slug: 'beverly-hills-california', state: 'California' },
  { name: 'Bishop', slug: 'bishop-california', state: 'California' },
  { name: 'Brawley', slug: 'brawley-california', state: 'California' },
  { name: 'Brea', slug: 'brea-california', state: 'California' },
  { name: 'Brentwood', slug: 'brentwood-california', state: 'California' },
  { name: 'Buena Park', slug: 'buena-park-california', state: 'California' },
  { name: 'Burbank', slug: 'burbank-california', state: 'California' },
  { name: 'Burlingame', slug: 'burlingame-california', state: 'California' },
  { name: 'Calexico', slug: 'calexico-california', state: 'California' },
  { name: 'Calimesa', slug: 'calimesa-california', state: 'California' },
  { name: 'Camarillo', slug: 'camarillo-california', state: 'California' },
  { name: 'Campbell', slug: 'campbell-california', state: 'California' },
  { name: 'Capitola', slug: 'capitola-california', state: 'California' },
  { name: 'Carpentersville', slug: 'carpentersville-california', state: 'California' },
  { name: 'Carpinteria', slug: 'carpinteria-california', state: 'California' },
  { name: 'Carson', slug: 'carson-california', state: 'California' },
  { name: 'Castro Valley', slug: 'castro-valley-california', state: 'California' },
  { name: 'Cathedral City', slug: 'cathedral-city-california', state: 'California' },
  { name: 'Ceres', slug: 'ceres-california', state: 'California' },
  { name: 'Cerritos', slug: 'cerritos-california', state: 'California' },
  { name: 'Chico', slug: 'chico-california', state: 'California' },
  { name: 'Chino', slug: 'chino-california', state: 'California' },
  { name: 'Chino Hills', slug: 'chino-hills-california', state: 'California' },
  { name: 'Chula Vista', slug: 'chula-vista-california', state: 'California' },
  { name: 'Citrus Heights', slug: 'citrus-heights-california', state: 'California' },
  { name: 'Claremont', slug: 'claremont-california', state: 'California' },
  { name: 'Clayton', slug: 'clayton-california', state: 'California' },
  { name: 'Clearlake', slug: 'clearlake-california', state: 'California' },
  { name: 'Cloverdale', slug: 'cloverdale-california', state: 'California' },
  { name: 'Clovis', slug: 'clovis-california', state: 'California' },
  { name: 'Coachella', slug: 'coachella-california', state: 'California' },
  { name: 'Colton', slug: 'colton-california', state: 'California' },
  { name: 'Colusa', slug: 'colusa-california', state: 'California' },
  { name: 'Compton', slug: 'compton-california', state: 'California' },
  { name: 'Concord', slug: 'concord-california', state: 'California' },
  { name: 'Corcoran', slug: 'corcoran-california', state: 'California' },
  { name: 'Corona', slug: 'corona-california', state: 'California' },
  { name: 'Coronado', slug: 'coronado-california', state: 'California' },
  { name: 'Corte Madera', slug: 'corte-madera-california', state: 'California' },
  { name: 'Covina', slug: 'covina-california', state: 'California' },
  { name: 'Cudahy', slug: 'cudahy-california', state: 'California' },
  { name: 'Culver City', slug: 'culver-city-california', state: 'California' },
  { name: 'Cupertino', slug: 'cupertino-california', state: 'California' },
  { name: 'Cypress', slug: 'cypress-california', state: 'California' },
  { name: 'Daly City', slug: 'daly-city-california', state: 'California' },
  { name: 'Danville', slug: 'danville-california', state: 'California' },
  { name: 'Davis', slug: 'davis-california', state: 'California' },
  { name: 'Delano', slug: 'delano-california', state: 'California' },
  { name: 'Desert Hot Springs', slug: 'desert-hot-springs-california', state: 'California' },
  { name: 'Diamond Bar', slug: 'diamond-bar-california', state: 'California' },
  { name: 'Dinuba', slug: 'dinuba-california', state: 'California' },
  { name: 'Dixon', slug: 'dixon-california', state: 'California' },
  { name: 'Downey', slug: 'downey-california', state: 'California' },
  { name: 'Duarte', slug: 'duarte-california', state: 'California' },
  { name: 'Dublin', slug: 'dublin-california', state: 'California' },
  { name: 'East Palo Alto', slug: 'east-palo-alto-california', state: 'California' },
  { name: 'El Cajon', slug: 'el-cajon-california', state: 'California' },
  { name: 'El Centro', slug: 'el-centro-california', state: 'California' },
  { name: 'El Cerrito', slug: 'el-cerrito-california', state: 'California' },
  { name: 'El Monte', slug: 'el-monte-california', state: 'California' },
  { name: 'El Segundo', slug: 'el-segundo-california', state: 'California' },
  { name: 'Elk Grove', slug: 'elk-grove-california', state: 'California' },
  { name: 'Emeryville', slug: 'emeryville-california', state: 'California' },
  { name: 'Encinitas', slug: 'encinitas-california', state: 'California' },
  { name: 'Escondido', slug: 'escondido-california', state: 'California' },
  { name: 'Eureka', slug: 'eureka-california', state: 'California' },
  { name: 'Fairfield', slug: 'fairfield-california', state: 'California' },
  { name: 'Farmersville', slug: 'farmersville-california', state: 'California' },
  { name: 'Folsom', slug: 'folsom-california', state: 'California' },
  { name: 'Fontana', slug: 'fontana-california', state: 'California' },
  { name: 'Foster City', slug: 'foster-city-california', state: 'California' },
  { name: 'Fountain Valley', slug: 'fountain-valley-california', state: 'California' },
  { name: 'Fremont', slug: 'fremont-california', state: 'California' },
  { name: 'Fresno', slug: 'fresno-california', state: 'California' },
  { name: 'Fullerton', slug: 'fullerton-california', state: 'California' },
  { name: 'Garden Grove', slug: 'garden-grove-california', state: 'California' },
  { name: 'Gardena', slug: 'gardena-california', state: 'California' },
  { name: 'Gilroy', slug: 'gilroy-california', state: 'California' },
  { name: 'Glendale', slug: 'glendale-california', state: 'California' },
  { name: 'Glendora', slug: 'glendora-california', state: 'California' },
  { name: 'Goleta', slug: 'goleta-california', state: 'California' },
  { name: 'Grand Terrace', slug: 'grand-terrace-california', state: 'California' },
  { name: 'Grass Valley', slug: 'grass-valley-california', state: 'California' },
  { name: 'Greenfield', slug: 'greenfield-california', state: 'California' },
  { name: 'Grover Beach', slug: 'grover-beach-california', state: 'California' },
  { name: 'Half Moon Bay', slug: 'half-moon-bay-california', state: 'California' },
  { name: 'Hanford', slug: 'hanford-california', state: 'California' },
  { name: 'Hawaiian Gardens', slug: 'hawaiian-gardens-california', state: 'California' },
  { name: 'Hawthorne', slug: 'hawthorne-california', state: 'California' },
  { name: 'Hayward', slug: 'hayward-california', state: 'California' },
  { name: 'Healdsburg', slug: 'healdsburg-california', state: 'California' },
  { name: 'Hemet', slug: 'hemet-california', state: 'California' },
  { name: 'Hercules', slug: 'hercules-california', state: 'California' },
  { name: 'Hermosa Beach', slug: 'hermosa-beach-california', state: 'California' },
  { name: 'Hesperia', slug: 'hesperia-california', state: 'California' },
  { name: 'Highland', slug: 'highland-california', state: 'California' },
  { name: 'Hillsborough', slug: 'hillsborough-california', state: 'California' },
  { name: 'Hollister', slug: 'hollister-california', state: 'California' },
  { name: 'Huntington Beach', slug: 'huntington-beach-california', state: 'California' },
  { name: 'Huntington Park', slug: 'huntington-park-california', state: 'California' },
  { name: 'Imperial Beach', slug: 'imperial-beach-california', state: 'California' },
  { name: 'Indian Wells', slug: 'indian-wells-california', state: 'California' },
  { name: 'Indio', slug: 'indio-california', state: 'California' },
  { name: 'Industry', slug: 'industry-california', state: 'California' },
  { name: 'Inglewood', slug: 'inglewood-california', state: 'California' },
  { name: 'Irvine', slug: 'irvine-california', state: 'California' },
  { name: 'Isleton', slug: 'isleton-california', state: 'California' },
  { name: 'Jackson', slug: 'jackson-california', state: 'California' },
  { name: 'La Canada Flintridge', slug: 'la-canada-flintridge-california', state: 'California' },
  { name: 'La Habra', slug: 'la-habra-california', state: 'California' },
  { name: 'La Mesa', slug: 'la-mesa-california', state: 'California' },
  { name: 'La Mirada', slug: 'la-mirada-california', state: 'California' },
  { name: 'La Palma', slug: 'la-palma-california', state: 'California' },
  { name: 'La Puente', slug: 'la-puente-california', state: 'California' },
  { name: 'La Quinta', slug: 'la-quinta-california', state: 'California' },
  { name: 'La Verne', slug: 'la-verne-california', state: 'California' },
  { name: 'Lafayette', slug: 'lafayette-california', state: 'California' },
  { name: 'Laguna Beach', slug: 'laguna-beach-california', state: 'California' },
  { name: 'Laguna Hills', slug: 'laguna-hills-california', state: 'California' },
  { name: 'Laguna Niguel', slug: 'laguna-niguel-california', state: 'California' },
  { name: 'Laguna Woods', slug: 'laguna-woods-california', state: 'California' },
  { name: 'Lake Elsinore', slug: 'lake-elsinore-california', state: 'California' },
  { name: 'Lake Forest', slug: 'lake-forest-california', state: 'California' },
  { name: 'Lakewood', slug: 'lakewood-california', state: 'California' },
  { name: 'Lancaster', slug: 'lancaster-california', state: 'California' },
  { name: 'Larkspur', slug: 'larkspur-california', state: 'California' },
  { name: 'Lathrop', slug: 'lathrop-california', state: 'California' },
  { name: 'Lawndale', slug: 'lawndale-california', state: 'California' },
  { name: 'Lemon Grove', slug: 'lemon-grove-california', state: 'California' },
  { name: 'Lemoore', slug: 'lemoore-california', state: 'California' },
  { name: 'Lincoln', slug: 'lincoln-california', state: 'California' },
  { name: 'Livermore', slug: 'livermore-california', state: 'California' },
  { name: 'Livingston', slug: 'livingston-california', state: 'California' },
  { name: 'Lodi', slug: 'lodi-california', state: 'California' },
  { name: 'Loma Linda', slug: 'loma-linda-california', state: 'California' },
  { name: 'Lomita', slug: 'lomita-california', state: 'California' },
  { name: 'Lompoc', slug: 'lompoc-california', state: 'California' },
  { name: 'Long Beach', slug: 'long-beach-california', state: 'California' },
  { name: 'Los Alamitos', slug: 'los-alamitos-california', state: 'California' },
  { name: 'Los Altos', slug: 'los-altos-california', state: 'California' },
  { name: 'Los Altos Hills', slug: 'los-altos-hills-california', state: 'California' },
  { name: 'Los Angeles', slug: 'los-angeles-california', state: 'California' },
  { name: 'Los Banos', slug: 'los-banos-california', state: 'California' },
  { name: 'Los Gatos', slug: 'los-gatos-california', state: 'California' },
  { name: 'Lynwood', slug: 'lynwood-california', state: 'California' },
  { name: 'Madera', slug: 'madera-california', state: 'California' },
  { name: 'Malibu', slug: 'malibu-california', state: 'California' },
  { name: 'Mammoth Lakes', slug: 'mammoth-lakes-california', state: 'California' },
  { name: 'Manhattan Beach', slug: 'manhattan-beach-california', state: 'California' },
  { name: 'Manteca', slug: 'manteca-california', state: 'California' },
  { name: 'Marina', slug: 'marina-california', state: 'California' },
  { name: 'Martinez', slug: 'martinez-california', state: 'California' },
  { name: 'Marysville', slug: 'marysville-california', state: 'California' },
  { name: 'Maywood', slug: 'maywood-california', state: 'California' },
  { name: 'McFarland', slug: 'mcfarland-california', state: 'California' },
  { name: 'Menifee', slug: 'menifee-california', state: 'California' },
  { name: 'Menlo Park', slug: 'menlo-park-california', state: 'California' },
  { name: 'Merced', slug: 'merced-california', state: 'California' },
  { name: 'Millbrae', slug: 'millbrae-california', state: 'California' },
  { name: 'Milpitas', slug: 'milpitas-california', state: 'California' },
  { name: 'Mission Viejo', slug: 'mission-viejo-california', state: 'California' },
  { name: 'Modesto', slug: 'modesto-california', state: 'California' },
  { name: 'Monrovia', slug: 'monrovia-california', state: 'California' },
  { name: 'Montclair', slug: 'montclair-california', state: 'California' },
  { name: 'Montebello', slug: 'montebello-california', state: 'California' },
  { name: 'Monterey', slug: 'monterey-california', state: 'California' },
  { name: 'Monterey Park', slug: 'monterey-park-california', state: 'California' },
  { name: 'Moorpark', slug: 'moorpark-california', state: 'California' },
  { name: 'Moraga', slug: 'moraga-california', state: 'California' },
  { name: 'Moreno Valley', slug: 'moreno-valley-california', state: 'California' },
  { name: 'Morgan Hill', slug: 'morgan-hill-california', state: 'California' },
  { name: 'Morro Bay', slug: 'morro-bay-california', state: 'California' },
  { name: 'Mountain View', slug: 'mountain-view-california', state: 'California' },
  { name: 'Murrieta', slug: 'murrieta-california', state: 'California' },
  { name: 'Napa', slug: 'napa-california', state: 'California' },
  { name: 'National City', slug: 'national-city-california', state: 'California' },
  { name: 'Needles', slug: 'needles-california', state: 'California' },
  { name: 'Newark', slug: 'newark-california', state: 'California' },
  { name: 'Newman', slug: 'newman-california', state: 'California' },
  { name: 'Newport Beach', slug: 'newport-beach-california', state: 'California' },
  { name: 'Norco', slug: 'norco-california', state: 'California' },
  { name: 'Norwalk', slug: 'norwalk-california', state: 'California' },
  { name: 'Novato', slug: 'novato-california', state: 'California' },
  { name: 'Oakland', slug: 'oakland-california', state: 'California' },
  { name: 'Oakley', slug: 'oakley-california', state: 'California' },
  { name: 'Oceanside', slug: 'oceanside-california', state: 'California' },
  { name: 'Ojai', slug: 'ojai-california', state: 'California' },
  { name: 'Ontario', slug: 'ontario-california', state: 'California' },
  { name: 'Orange', slug: 'orange-california', state: 'California' },
  { name: 'Orange Cove', slug: 'orange-cove-california', state: 'California' },
  { name: 'Orinda', slug: 'orinda-california', state: 'California' },
  { name: 'Orland', slug: 'orland-california', state: 'California' },
  { name: 'Oroville', slug: 'oroville-california', state: 'California' },
  { name: 'Oxnard', slug: 'oxnard-california', state: 'California' },
  { name: 'Pacific Grove', slug: 'pacific-grove-california', state: 'California' },
  { name: 'Pacifica', slug: 'pacifica-california', state: 'California' },
  { name: 'Palm Desert', slug: 'palm-desert-california', state: 'California' },
  { name: 'Palm Springs', slug: 'palm-springs-california', state: 'California' },
  { name: 'Palmdale', slug: 'palmdale-california', state: 'California' },
  { name: 'Palo Alto', slug: 'palo-alto-california', state: 'California' },
  { name: 'Palos Verdes Estates', slug: 'palos-verdes-estates-california', state: 'California' },
  { name: 'Paradise', slug: 'paradise-california', state: 'California' },
  { name: 'Paramount', slug: 'paramount-california', state: 'California' },
  { name: 'Pasadena', slug: 'pasadena-california', state: 'California' },
  { name: 'Paso Robles', slug: 'paso-robles-california', state: 'California' },
  { name: 'Patterson', slug: 'patterson-california', state: 'California' },
  { name: 'Perris', slug: 'perris-california', state: 'California' },
  { name: 'Petaluma', slug: 'petaluma-california', state: 'California' },
  { name: 'Pico Rivera', slug: 'pico-rivera-california', state: 'California' },
  { name: 'Piedmont', slug: 'piedmont-california', state: 'California' },
  { name: 'Pinole', slug: 'pinole-california', state: 'California' },
  { name: 'Pismo Beach', slug: 'pismo-beach-california', state: 'California' },
  { name: 'Pittsburg', slug: 'pittsburg-california', state: 'California' },
  { name: 'Placentia', slug: 'placentia-california', state: 'California' },
  { name: 'Pleasant Hill', slug: 'pleasant-hill-california', state: 'California' },
  { name: 'Pleasanton', slug: 'pleasanton-california', state: 'California' },
  { name: 'Pomona', slug: 'pomona-california', state: 'California' },
  { name: 'Port Hueneme', slug: 'port-hueneme-california', state: 'California' },
  { name: 'Porterville', slug: 'porterville-california', state: 'California' },
  { name: 'Poway', slug: 'poway-california', state: 'California' },
  { name: 'Rancho Cordova', slug: 'rancho-cordova-california', state: 'California' },
  { name: 'Rancho Cucamonga', slug: 'rancho-cucamonga-california', state: 'California' },
  { name: 'Rancho Mirage', slug: 'rancho-mirage-california', state: 'California' },
  { name: 'Rancho Palos Verdes', slug: 'rancho-palos-verdes-california', state: 'California' },
  { name: 'Rancho Santa Margarita', slug: 'rancho-santa-margarita-california', state: 'California' },
  { name: 'Red Bluff', slug: 'red-bluff-california', state: 'California' },
  { name: 'Redding', slug: 'redding-california', state: 'California' },
  { name: 'Redlands', slug: 'redlands-california', state: 'California' },
  { name: 'Redondo Beach', slug: 'redondo-beach-california', state: 'California' },
  { name: 'Redwood City', slug: 'redwood-city-california', state: 'California' },
  { name: 'Reedley', slug: 'reedley-california', state: 'California' },
  { name: 'Rialto', slug: 'rialto-california', state: 'California' },
  { name: 'Richmond', slug: 'richmond-california', state: 'California' },
  { name: 'Ridgecrest', slug: 'ridgecrest-california', state: 'California' },
  { name: 'Rio Vista', slug: 'rio-vista-california', state: 'California' },
  { name: 'Ripon', slug: 'ripon-california', state: 'California' },
  { name: 'Riverbank', slug: 'riverbank-california', state: 'California' },
  { name: 'Riverside', slug: 'riverside-california', state: 'California' },
  { name: 'Rocklin', slug: 'rocklin-california', state: 'California' },
  { name: 'Rohnert Park', slug: 'rohnert-park-california', state: 'California' },
  { name: 'Rosemead', slug: 'rosemead-california', state: 'California' },
  { name: 'Roseville', slug: 'roseville-california', state: 'California' },
  { name: 'Sacramento', slug: 'sacramento-california', state: 'California' },
  { name: 'Salinas', slug: 'salinas-california', state: 'California' },
  { name: 'San Bernardino', slug: 'san-bernardino-california', state: 'California' },
  { name: 'San Bruno', slug: 'san-bruno-california', state: 'California' },
  { name: 'San Carlos', slug: 'san-carlos-california', state: 'California' },
  { name: 'San Clemente', slug: 'san-clemente-california', state: 'California' },
  { name: 'San Diego', slug: 'san-diego-california', state: 'California' },
  { name: 'San Fernando', slug: 'san-fernando-california', state: 'California' },
  { name: 'San Francisco', slug: 'san-francisco-california', state: 'California' },
  { name: 'San Gabriel', slug: 'san-gabriel-california', state: 'California' },
  { name: 'San Jacinto', slug: 'san-jacinto-california', state: 'California' },
  { name: 'San Jose', slug: 'san-jose-california', state: 'California' },
  { name: 'San Juan Capistrano', slug: 'san-juan-capistrano-california', state: 'California' },
  { name: 'San Leandro', slug: 'san-leandro-california', state: 'California' },
  { name: 'San Luis Obispo', slug: 'san-luis-obispo-california', state: 'California' },
  { name: 'San Marcos', slug: 'san-marcos-california', state: 'California' },
  { name: 'San Marino', slug: 'san-marino-california', state: 'California' },
  { name: 'San Mateo', slug: 'san-mateo-california', state: 'California' },
  { name: 'San Pablo', slug: 'san-pablo-california', state: 'California' },
  { name: 'San Rafael', slug: 'san-rafael-california', state: 'California' },
  { name: 'San Ramon', slug: 'san-ramon-california', state: 'California' },
  { name: 'Sanger', slug: 'sanger-california', state: 'California' },
  { name: 'Santa Ana', slug: 'santa-ana-california', state: 'California' },
  { name: 'Santa Barbara', slug: 'santa-barbara-california', state: 'California' },
  { name: 'Santa Clara', slug: 'santa-clara-california', state: 'California' },
  { name: 'Santa Clarita', slug: 'santa-clarita-california', state: 'California' },
  { name: 'Santa Cruz', slug: 'santa-cruz-california', state: 'California' },
  { name: 'Santa Fe Springs', slug: 'santa-fe-springs-california', state: 'California' },
  { name: 'Santa Maria', slug: 'santa-maria-california', state: 'California' },
  { name: 'Santa Monica', slug: 'santa-monica-california', state: 'California' },
  { name: 'Santa Paula', slug: 'santa-paula-california', state: 'California' },
  { name: 'Santa Rosa', slug: 'santa-rosa-california', state: 'California' },
  { name: 'Santee', slug: 'santee-california', state: 'California' },
  { name: 'Saratoga', slug: 'saratoga-california', state: 'California' },
  { name: 'Sausalito', slug: 'sausalito-california', state: 'California' },
  { name: 'Scotts Valley', slug: 'scotts-valley-california', state: 'California' },
  { name: 'Seal Beach', slug: 'seal-beach-california', state: 'California' },
  { name: 'Seaside', slug: 'seaside-california', state: 'California' },
  { name: 'Sebastopol', slug: 'sebastopol-california', state: 'California' },
  { name: 'Selma', slug: 'selma-california', state: 'California' },
  { name: 'Shafter', slug: 'shafter-california', state: 'California' },
  { name: 'Signal Hill', slug: 'signal-hill-california', state: 'California' },
  { name: 'Simi Valley', slug: 'simi-valley-california', state: 'California' },
  { name: 'Solana Beach', slug: 'solana-beach-california', state: 'California' },
  { name: 'Soledad', slug: 'soledad-california', state: 'California' },
  { name: 'Solvang', slug: 'solvang-california', state: 'California' },
  { name: 'Sonoma', slug: 'sonoma-california', state: 'California' },
  { name: 'Sonora', slug: 'sonora-california', state: 'California' },
  { name: 'South El Monte', slug: 'south-el-monte-california', state: 'California' },
  { name: 'South Gate', slug: 'south-gate-california', state: 'California' },
  { name: 'South Lake Tahoe', slug: 'south-lake-tahoe-california', state: 'California' },
  { name: 'South Pasadena', slug: 'south-pasadena-california', state: 'California' },
  { name: 'South San Francisco', slug: 'south-san-francisco-california', state: 'California' },
  { name: 'Stanton', slug: 'stanton-california', state: 'California' },
  { name: 'Stockton', slug: 'stockton-california', state: 'California' },
  { name: 'Suisun City', slug: 'suisun-city-california', state: 'California' },
  { name: 'Sunnyvale', slug: 'sunnyvale-california', state: 'California' },
  { name: 'Susanville', slug: 'susanville-california', state: 'California' },
  { name: 'Taft', slug: 'taft-california', state: 'California' },
  { name: 'Tehachapi', slug: 'tehachapi-california', state: 'California' },
  { name: 'Temecula', slug: 'temecula-california', state: 'California' },
  { name: 'Temple City', slug: 'temple-city-california', state: 'California' },
  { name: 'Thousand Oaks', slug: 'thousand-oaks-california', state: 'California' },
  { name: 'Torrance', slug: 'torrance-california', state: 'California' },
  { name: 'Tracy', slug: 'tracy-california', state: 'California' },
  { name: 'Truckee', slug: 'truckee-california', state: 'California' },
  { name: 'Tulare', slug: 'tulare-california', state: 'California' },
  { name: 'Turlock', slug: 'turlock-california', state: 'California' },
  { name: 'Tustin', slug: 'tustin-california', state: 'California' },
  { name: 'Twentynine Palms', slug: 'twentynine-palms-california', state: 'California' },
  { name: 'Ukiah', slug: 'ukiah-california', state: 'California' },
  { name: 'Union City', slug: 'union-city-california', state: 'California' },
  { name: 'Upland', slug: 'upland-california', state: 'California' },
  { name: 'Vacaville', slug: 'vacaville-california', state: 'California' },
  { name: 'Vallejo', slug: 'vallejo-california', state: 'California' },
  { name: 'Ventura', slug: 'ventura-california', state: 'California' },
  { name: 'Vernon', slug: 'vernon-california', state: 'California' },
  { name: 'Victorville', slug: 'victorville-california', state: 'California' },
  { name: 'Vista', slug: 'vista-california', state: 'California' },
  { name: 'Walnut', slug: 'walnut-california', state: 'California' },
  { name: 'Walnut Creek', slug: 'walnut-creek-california', state: 'California' },
  { name: 'Wasco', slug: 'wasco-california', state: 'California' },
  { name: 'Waterford', slug: 'waterford-california', state: 'California' },
  { name: 'Watsonville', slug: 'watsonville-california', state: 'California' },
  { name: 'West Covina', slug: 'west-covina-california', state: 'California' },
  { name: 'West Hollywood', slug: 'west-hollywood-california', state: 'California' },
  { name: 'West Sacramento', slug: 'west-sacramento-california', state: 'California' },
  { name: 'Westminster', slug: 'westminster-california', state: 'California' },
  { name: 'Whittier', slug: 'whittier-california', state: 'California' },
  { name: 'Wildomar', slug: 'wildomar-california', state: 'California' },
  { name: 'Willows', slug: 'willows-california', state: 'California' },
  { name: 'Windsor', slug: 'windsor-california', state: 'California' },
  { name: 'Winters', slug: 'winters-california', state: 'California' },
  { name: 'Woodland', slug: 'woodland-california', state: 'California' },
  { name: 'Woodlake', slug: 'woodlake-california', state: 'California' },
  { name: 'Yreka', slug: 'yreka-california', state: 'California' },
  { name: 'Yuba City', slug: 'yuba-city-california', state: 'California' },
  { name: 'Yucaipa', slug: 'yucaipa-california', state: 'California' },
  { name: 'Yucca Valley', slug: 'yucca-valley-california', state: 'California' },
  
  // Colorado cities - continuing with comprehensive list
  { name: 'Alamosa', slug: 'alamosa-colorado', state: 'Colorado' },
  { name: 'Arvada', slug: 'arvada-colorado', state: 'Colorado' },
  { name: 'Aspen', slug: 'aspen-colorado', state: 'Colorado' },
  { name: 'Aurora', slug: 'aurora-colorado', state: 'Colorado' },
  { name: 'Boulder', slug: 'boulder-colorado', state: 'Colorado' },
  { name: 'Broomfield', slug: 'broomfield-colorado', state: 'Colorado' },
  { name: 'Castle Rock', slug: 'castle-rock-colorado', state: 'Colorado' },
  { name: 'Centennial', slug: 'centennial-colorado', state: 'Colorado' },
  { name: 'Colorado Springs', slug: 'colorado-springs-colorado', state: 'Colorado' },
  { name: 'Commerce City', slug: 'commerce-city-colorado', state: 'Colorado' },
  { name: 'Denver', slug: 'denver-colorado', state: 'Colorado' },
  { name: 'Durango', slug: 'durango-colorado', state: 'Colorado' },
  { name: 'Englewood', slug: 'englewood-colorado', state: 'Colorado' },
  { name: 'Fort Collins', slug: 'fort-collins-colorado', state: 'Colorado' },
  { name: 'Grand Junction', slug: 'grand-junction-colorado', state: 'Colorado' },
  { name: 'Greeley', slug: 'greeley-colorado', state: 'Colorado' },
  { name: 'Lakewood', slug: 'lakewood-colorado', state: 'Colorado' },
  { name: 'Littleton', slug: 'littleton-colorado', state: 'Colorado' },
  { name: 'Longmont', slug: 'longmont-colorado', state: 'Colorado' },
  { name: 'Loveland', slug: 'loveland-colorado', state: 'Colorado' },
  { name: 'Pueblo', slug: 'pueblo-colorado', state: 'Colorado' },
  { name: 'Thornton', slug: 'thornton-colorado', state: 'Colorado' },
  { name: 'Westminster', slug: 'westminster-colorado', state: 'Colorado' },
  { name: 'Wheat Ridge', slug: 'wheat-ridge-colorado', state: 'Colorado' },
  
  // Connecticut cities
  { name: 'Bridgeport', slug: 'bridgeport-connecticut', state: 'Connecticut' },
  { name: 'Bristol', slug: 'bristol-connecticut', state: 'Connecticut' },
  { name: 'Danbury', slug: 'danbury-connecticut', state: 'Connecticut' },
  { name: 'Hartford', slug: 'hartford-connecticut', state: 'Connecticut' },
  { name: 'Meriden', slug: 'meriden-connecticut', state: 'Connecticut' },
  { name: 'Middletown', slug: 'middletown-connecticut', state: 'Connecticut' },
  { name: 'Milford', slug: 'milford-connecticut', state: 'Connecticut' },
  { name: 'New Britain', slug: 'new-britain-connecticut', state: 'Connecticut' },
  { name: 'New Haven', slug: 'new-haven-connecticut', state: 'Connecticut' },
  { name: 'New London', slug: 'new-london-connecticut', state: 'Connecticut' },
  { name: 'Norwalk', slug: 'norwalk-connecticut', state: 'Connecticut' },
  { name: 'Norwich', slug: 'norwich-connecticut', state: 'Connecticut' },
  { name: 'Stamford', slug: 'stamford-connecticut', state: 'Connecticut' },
  { name: 'Stratford', slug: 'stratford-connecticut', state: 'Connecticut' },
  { name: 'Waterbury', slug: 'waterbury-connecticut', state: 'Connecticut' },
  { name: 'West Haven', slug: 'west-haven-connecticut', state: 'Connecticut' },
  
  // Delaware cities
  { name: 'Bear', slug: 'bear-delaware', state: 'Delaware' },
  { name: 'Dover', slug: 'dover-delaware', state: 'Delaware' },
  { name: 'Newark', slug: 'newark-delaware', state: 'Delaware' },
  { name: 'Wilmington', slug: 'wilmington-delaware', state: 'Delaware' },
  
  // Florida cities - adding more
  { name: 'Altamonte Springs', slug: 'altamonte-springs-florida', state: 'Florida' },
  { name: 'Apalachicola', slug: 'apalachicola-florida', state: 'Florida' },
  { name: 'Apopka', slug: 'apopka-florida', state: 'Florida' },
  { name: 'Arcadia', slug: 'arcadia-florida', state: 'Florida' },
  { name: 'Bartow', slug: 'bartow-florida', state: 'Florida' },
  { name: 'Belle Glade', slug: 'belle-glade-florida', state: 'Florida' },
  { name: 'Belleview', slug: 'belleview-florida', state: 'Florida' },
  { name: 'Blountstown', slug: 'blountstown-florida', state: 'Florida' },
  { name: 'Bonita Springs', slug: 'bonita-springs-florida', state: 'Florida' },
  { name: 'Bradenton', slug: 'bradenton-florida', state: 'Florida' },
  { name: 'Bristol', slug: 'bristol-florida', state: 'Florida' },
  { name: 'Brooksville', slug: 'brooksville-florida', state: 'Florida' },
  { name: 'Bunnell', slug: 'bunnell-florida', state: 'Florida' },
  { name: 'Callaway', slug: 'callaway-florida', state: 'Florida' },
  { name: 'Cape Canaveral', slug: 'cape-canaveral-florida', state: 'Florida' },
  { name: 'Cape Coral', slug: 'cape-coral-florida', state: 'Florida' },
  { name: 'Carrabelle', slug: 'carrabelle-florida', state: 'Florida' },
  { name: 'Cedar Key', slug: 'cedar-key-florida', state: 'Florida' },
  { name: 'Chattahoochee', slug: 'chattahoochee-florida', state: 'Florida' },
  { name: 'Chiefland', slug: 'chiefland-florida', state: 'Florida' },
  { name: 'Clearwater', slug: 'clearwater-florida', state: 'Florida' },
  { name: 'Clermont', slug: 'clermont-florida', state: 'Florida' },
  { name: 'Clewiston', slug: 'clewiston-florida', state: 'Florida' },
  { name: 'Cocoa', slug: 'cocoa-florida', state: 'Florida' },
  { name: 'Cocoa Beach', slug: 'cocoa-beach-florida', state: 'Florida' },
  { name: 'Coconut Creek', slug: 'coconut-creek-florida', state: 'Florida' },
  { name: 'Coral Gables', slug: 'coral-gables-florida', state: 'Florida' },
  { name: 'Coral Springs', slug: 'coral-springs-florida', state: 'Florida' },
  { name: 'Crescent City', slug: 'crescent-city-florida', state: 'Florida' },
  { name: 'Crestview', slug: 'crestview-florida', state: 'Florida' },
  { name: 'Cross City', slug: 'cross-city-florida', state: 'Florida' },
  { name: 'Crystal River', slug: 'crystal-river-florida', state: 'Florida' },
  { name: 'Dade City', slug: 'dade-city-florida', state: 'Florida' },
  { name: 'Dania Beach', slug: 'dania-beach-florida', state: 'Florida' },
  { name: 'Davenport', slug: 'davenport-florida', state: 'Florida' },
  { name: 'Daytona Beach', slug: 'daytona-beach-florida', state: 'Florida' },
  { name: 'De Funiak Springs', slug: 'de-funiak-springs-florida', state: 'Florida' },
  { name: 'DeLand', slug: 'deland-florida', state: 'Florida' },
  { name: 'Deerfield Beach', slug: 'deerfield-beach-florida', state: 'Florida' },
  { name: 'Delray Beach', slug: 'delray-beach-florida', state: 'Florida' },
  { name: 'Deltona', slug: 'deltona-florida', state: 'Florida' },
  { name: 'Destin', slug: 'destin-florida', state: 'Florida' },
  { name: 'Dunedin', slug: 'dunedin-florida', state: 'Florida' },
  { name: 'Eustis', slug: 'eustis-florida', state: 'Florida' },
  { name: 'Fernandina Beach', slug: 'fernandina-beach-florida', state: 'Florida' },
  { name: 'Fort Lauderdale', slug: 'fort-lauderdale-florida', state: 'Florida' },
  { name: 'Fort Meade', slug: 'fort-meade-florida', state: 'Florida' },
  { name: 'Fort Myers', slug: 'fort-myers-florida', state: 'Florida' },
  { name: 'Fort Pierce', slug: 'fort-pierce-florida', state: 'Florida' },
  { name: 'Fort Walton Beach', slug: 'fort-walton-beach-florida', state: 'Florida' },
  { name: 'Gainesville', slug: 'gainesville-florida', state: 'Florida' },
  { name: 'Glen Ridge', slug: 'glen-ridge-florida', state: 'Florida' },
  { name: 'Greenacres', slug: 'greenacres-florida', state: 'Florida' },
  { name: 'Green Cove Springs', slug: 'green-cove-springs-florida', state: 'Florida' },
  { name: 'Gulf Breeze', slug: 'gulf-breeze-florida', state: 'Florida' },
  { name: 'Haines City', slug: 'haines-city-florida', state: 'Florida' },
  { name: 'Hallandale Beach', slug: 'hallandale-beach-florida', state: 'Florida' },
  { name: 'Hialeah', slug: 'hialeah-florida', state: 'Florida' },
  { name: 'High Springs', slug: 'high-springs-florida', state: 'Florida' },
  { name: 'Holly Hill', slug: 'holly-hill-florida', state: 'Florida' },
  { name: 'Hollywood', slug: 'holly wood-florida', state: 'Florida' },
  { name: 'Homestead', slug: 'homestead-florida', state: 'Florida' },
  { name: 'Immokalee', slug: 'immokalee-florida', state: 'Florida' },
  { name: 'Inverness', slug: 'inverness-florida', state: 'Florida' },
  { name: 'Jacksonville', slug: 'jacksonville-florida', state: 'Florida' },
  { name: 'Jacksonville Beach', slug: 'jacksonville-beach-florida', state: 'Florida' },
  { name: 'Jasper', slug: 'jasper-florida', state: 'Florida' },
  { name: 'Jupiter', slug: 'jupiter-florida', state: 'Florida' },
  { name: 'Key Largo', slug: 'key-largo-florida', state: 'Florida' },
  { name: 'Key West', slug: 'key-west-florida', state: 'Florida' },
  { name: 'Kissimmee', slug: 'kissimmee-florida', state: 'Florida' },
  { name: 'LaBelle', slug: 'labelle-florida', state: 'Florida' },
  { name: 'Lake City', slug: 'lake-city-florida', state: 'Florida' },
  { name: 'Lake Mary', slug: 'lake-mary-florida', state: 'Florida' },
  { name: 'Lake Placid', slug: 'lake-placid-florida', state: 'Florida' },
  { name: 'Lake Wales', slug: 'lake-wales-florida', state: 'Florida' },
  { name: 'Lake Worth', slug: 'lake-worth-florida', state: 'Florida' },
  { name: 'Lakeland', slug: 'lakeland-florida', state: 'Florida' },
  { name: 'Largo', slug: 'largo-florida', state: 'Florida' },
  { name: 'Lauderdale Lakes', slug: 'lauderdale-lakes-florida', state: 'Florida' },
  { name: 'Leesburg', slug: 'leesburg-florida', state: 'Florida' },
  { name: 'Live Oak', slug: 'live-oak-florida', state: 'Florida' },
  { name: 'Macclenny', slug: 'macclenny-florida', state: 'Florida' },
  { name: 'Madison', slug: 'madison-florida', state: 'Florida' },
  { name: 'Marathon', slug: 'marathon-florida', state: 'Florida' },
  { name: 'Marco Island', slug: 'marco-island-florida', state: 'Florida' },
  { name: 'Margate', slug: 'margate-florida', state: 'Florida' },
  { name: 'Mary Esther', slug: 'mary-esther-florida', state: 'Florida' },
  { name: 'Melbourne', slug: 'melbourne-florida', state: 'Florida' },
  { name: 'Miami', slug: 'miami-florida', state: 'Florida' },
  { name: 'Miami Beach', slug: 'miami-beach-florida', state: 'Florida' },
  { name: 'Miami Gardens', slug: 'miami-gardens-florida', state: 'Florida' },
  { name: 'Milton', slug: 'milton-florida', state: 'Florida' },
  { name: 'Miramar', slug: 'miramar-florida', state: 'Florida' },
  { name: 'Monticello', slug: 'monticello-florida', state: 'Florida' },
  { name: 'Mount Dora', slug: 'mount-dora-florida', state: 'Florida' },
  { name: 'Naples', slug: 'naples-florida', state: 'Florida' },
  { name: 'New Port Richey', slug: 'new-port-richey-florida', state: 'Florida' },
  { name: 'New Smyrna Beach', slug: 'new-smyrna-beach-florida', state: 'Florida' },
  { name: 'Niceville', slug: 'niceville-florida', state: 'Florida' },
  { name: 'North Miami', slug: 'north-miami-florida', state: 'Florida' },
  { name: 'North Miami Beach', slug: 'north-miami-beach-florida', state: 'Florida' },
  { name: 'North Port', slug: 'north-port-florida', state: 'Florida' },
  { name: 'Oakland Park', slug: 'oakland-park-florida', state: 'Florida' },
  { name: 'Ocala', slug: 'ocala-florida', state: 'Florida' },
  { name: 'Ocoee', slug: 'ocoee-florida', state: 'Florida' },
  { name: 'Okeechobee', slug: 'okeechobee-florida', state: 'Florida' },
  { name: 'Oldsmar', slug: 'oldsmar-florida', state: 'Florida' },
  { name: 'Orange City', slug: 'orange-city-florida', state: 'Florida' },
  { name: 'Orange Park', slug: 'orange-park-florida', state: 'Florida' },
  { name: 'Orlando', slug: 'orlando-florida', state: 'Florida' },
  { name: 'Orlando Metro', slug: 'orlando-metro-florida', state: 'Florida' },
  { name: 'Ormond Beach', slug: 'ormond-beach-florida', state: 'Florida' },
  { name: 'Oviedo', slug: 'oviedo-florida', state: 'Florida' },
  { name: 'Palatka', slug: 'palatka-florida', state: 'Florida' },
  { name: 'Palm Bay', slug: 'palm-bay-florida', state: 'Florida' },
  { name: 'Palm Beach', slug: 'palm-beach-florida', state: 'Florida' },
  { name: 'Palm Beach Gardens', slug: 'palm-beach-gardens-florida', state: 'Florida' },
  { name: 'Palm Coast', slug: 'palm-coast-florida', state: 'Florida' },
  { name: 'Palmetto', slug: 'palmetto-florida', state: 'Florida' },
  { name: 'Panama City', slug: 'panama-city-florida', state: 'Florida' },
  { name: 'Panama City Beach', slug: 'panama-city-beach-florida', state: 'Florida' },
  { name: 'Pembroke Pines', slug: 'pembroke-pines-florida', state: 'Florida' },
  { name: 'Pensacola', slug: 'pensacola-florida', state: 'Florida' },
  { name: 'Perry', slug: 'perry-florida', state: 'Florida' },
  { name: 'Plant City', slug: 'plant-city-florida', state: 'Florida' },
  { name: 'Plantation', slug: 'plantation-florida', state: 'Florida' },
  { name: 'Pompano Beach', slug: 'pompano-beach-florida', state: 'Florida' },
  { name: 'Ponce de Leon', slug: 'ponce-de-leon-florida', state: 'Florida' },
  { name: 'Port Charlotte', slug: 'port-charlotte-florida', state: 'Florida' },
  { name: 'Port Orange', slug: 'port-orange-florida', state: 'Florida' },
  { name: 'Port St. Lucie', slug: 'port-st-lucie-florida', state: 'Florida' },
  { name: 'Punta Gorda', slug: 'punta-gorda-florida', state: 'Florida' },
  { name: 'Quincy', slug: 'quincy-florida', state: 'Florida' },
  { name: 'Riviera Beach', slug: 'riviera-beach-florida', state: 'Florida' },
  { name: 'Rockledge', slug: 'rockledge-florida', state: 'Florida' },
  { name: 'Royal Palm Beach', slug: 'royal-palm-beach-florida', state: 'Florida' },
  { name: 'Safety Harbor', slug: 'safety-harbor-florida', state: 'Florida' },
  { name: 'Sanford', slug: 'sanford-florida', state: 'Florida' },
  { name: 'Sanibel', slug: 'sanibel-florida', state: 'Florida' },
  { name: 'Sarasota', slug: 'sarasota-florida', state: 'Florida' },
  { name: 'Satellite Beach', slug: 'satellite-beach-florida', state: 'Florida' },
  { name: 'Sebastian', slug: 'sebastian-florida', state: 'Florida' },
  { name: 'Sebring', slug: 'sebring-florida', state: 'Florida' },
  { name: 'Seminole', slug: 'seminole-florida', state: 'Florida' },
  { name: 'Shalimar', slug: 'shalimar-florida', state: 'Florida' },
  { name: 'St. Augustine', slug: 'st-augustine-florida', state: 'Florida' },
  { name: 'St. Cloud', slug: 'st-cloud-florida', state: 'Florida' },
  { name: 'St. Pete Beach', slug: 'st-pete-beach-florida', state: 'Florida' },
  { name: 'St. Petersburg', slug: 'st-petersburg-florida', state: 'Florida' },
  { name: 'Starke', slug: 'starke-florida', state: 'Florida' },
  { name: 'Stuart', slug: 'stuart-florida', state: 'Florida' },
  { name: 'Sunrise', slug: 'sunrise-florida', state: 'Florida' },
  { name: 'Tallahassee', slug: 'tallahassee-florida', state: 'Florida' },
  { name: 'Tamarac', slug: 'tamarac-florida', state: 'Florida' },
  { name: 'Tampa', slug: 'tampa-florida', state: 'Florida' },
  { name: 'Tarpon Springs', slug: 'tarpon-springs-florida', state: 'Florida' },
  { name: 'Tavares', slug: 'tavares-florida', state: 'Florida' },
  { name: 'Temple Terrace', slug: 'temple-terrace-florida', state: 'Florida' },
  { name: 'Titusville', slug: 'titusville-florida', state: 'Florida' },
  { name: 'Umatilla', slug: 'umatilla-florida', state: 'Florida' },
  { name: 'Valparaiso', slug: 'valparaiso-florida', state: 'Florida' },
  { name: 'Venice', slug: 'venice-florida', state: 'Florida' },
  { name: 'Vero Beach', slug: 'vero-beach-florida', state: 'Florida' },
  { name: 'Wauchula', slug: 'wauchula-florida', state: 'Florida' },
  { name: 'West Melbourne', slug: 'west-melbourne-florida', state: 'Florida' },
  { name: 'West Palm Beach', slug: 'west-palm-beach-florida', state: 'Florida' },
  { name: 'Weston', slug: 'weston-florida', state: 'Florida' },
  { name: 'Wildwood', slug: 'wildwood-florida', state: 'Florida' },
  { name: 'Williston', slug: 'williston-florida', state: 'Florida' },
  { name: 'Winter Garden', slug: 'winter-garden-florida', state: 'Florida' },
  { name: 'Winter Haven', slug: 'winter-haven-florida', state: 'Florida' },
  { name: 'Winter Park', slug: 'winter-park-florida', state: 'Florida' },
  { name: 'Winter Springs', slug: 'winter-springs-florida', state: 'Florida' },
  { name: 'Yulee', slug: 'yulee-florida', state: 'Florida' },
  { name: 'Zephyrhills', slug: 'zephyrhills-florida', state: 'Florida' },
  
  // Continue with more states to reach 500 total...
  // This is a partial list - the script continues with cities from other states
];

// Filter out cities that already exist
const newCities = citiesToCreate.filter(city => !existingCities.has(city.slug));

console.log(`Found ${citiesToCreate.length} total cities, ${newCities.length} new cities to create`);
console.log(`Filtering to first 500 new cities...`);

// Limit to 500 new cities
const citiesToGenerate = newCities.slice(0, 500);

// Continue in next part due to length...


